### ISSUE TITLE
odl.contrib vs. separate packages

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#1016]
We seem to agree that it would be nice to have a place to dump code that isn't maintained by the core devs. See also #951. There are two obvious options for this namely

1. add it to a subpackage `odl.contrib` or
2. make separate repos within the `odlgroup` GH organization.

### Subpackage

**Pros:**
- Minimal amount of code, just an addition within ODL
- Optimal visibility
- Motivation for outside contributors since it still feels like part of the "main" library, although less maintained

**Cons:**
- Makes main ODL larger
- The maintainers still have to keep an eye on PRs to not increase the size of the repo significantly (adding images, data, add + delete again huge amounts, ...)
- Issue of shipping (include? probably no)
- Kind of weird to have two quality standards within one single library

Some of these issues could be addressed with git submodules, but that makes them again harder to set up and use in practice.

### Separate repos

**Pros:**
- Separate, i.e., maintenance is up to the authors
- Lower requirements on accepting a new repo compared to a PR to main ODL
- Still good visibility since part of the main `odlgroup` organization (similar to what ZeroMQ does)
- No maintenance burden

**Cons:**
- Requires some boilerplate code, like a `setup.py` and an initial structure.
- Slightly less prominent in the ODL ecosystem.

The first counterargument could easily be addressed by providing a skeleton repo that provides all the basic structure and only requires an author of a new package to fill in some stuff.

**Comment by adler-j** [comment]
I'm personally in favor of a contrib package, mostly for the "Motivation for outside contributors since it still feels like part of the "main" library" reason. I also feel it would be weird to allow "external" users to add libraries under odlgroup (it causes lots of ownership issues).

So anyway, my suggestion is as follows:

* Add a `contrib` package for less maintained stuff. For me, the prime example would be #940 which is clearly a utility that lots of people would like to use, but adding it for @MatthiasJE is quite a hassle. Regarding the discussion in #1011, we could perhaps also add the LDDMM solver there.
* Keep larger stuff out of the repository. That includes any examples which require external resources, examples related to a specific article (except if it is an article with [1000+ citations](https://github.com/odlgroup/odl/blob/master/examples/solvers/douglas_rachford_pd_tomography_tv.py)), etc. Instead put them where ever people feel like having them under their own control. Personally, I keep a range of github repositories for this already.
* Get issue "Add "projects using ODL" to readme #701" done and add links to these repositories so we get some two-way exposure.

**Comment by kohr-h** [comment]
> I'm personally in favor of a contrib package, mostly for the "Motivation for outside contributors since it still feels like part of the "main" library" reason. I also feel it would be weird to allow "external" users to add libraries under odlgroup (it causes lots of ownership issues).

For `contrib` we then need some kind of guidelines on how to add stuff, see #1020.

**Comment by adler-j** [comment]
Are we happy with this now?

**Comment by kohr-h** [comment]
Yes, I think we have settled on this.
