### ISSUE TITLE
Compare `IdentityOperator`

### ISSUE THREAD

**Issue by chongchenmath** [odlgroup/odl#1038]
Can we compare `IdentityOperator`? If we can, the following example gives me an incredible result.

```python
import odl

space = odl.uniform_discr(min_pt=[-16, -16], max_pt=[16, 16], shape=[64, 64],
    dtype='float32', interp='linear')

op1 = odl.IdentityOperator(space)

op2 = odl.IdentityOperator(space)

print(op1 == op2)
```

Why is the result `False`?

**Comment by aringh** [comment]
I think you should use `isinstance(op1, odl.IdentityOperator)` to check if `op1` is an identity operator.

**Comment by kohr-h** [comment]
Operators have no equality check implemented, which means that `op1 == op2` is equivalent to `op1 is op2`, and that obviously evaluates to `False` in your case because the two are different objects.

In general it's difficult to check equality without missing obvious cases, for instance `IdentityOperator(space) == ScalingOperator(space, 1.0)` and similar.

What is the context of that question, maybe there's another way to achieve what you want?

**Comment by chongchenmath** [comment]
@aringh provided a good suggestion. 

A stupid question: Why the two are different objects? @kohr-h

**Comment by kohr-h** [comment]
> A stupid question: Why the two are different objects? @kohr-h

Because each time you call `IdentityOperator(space)` you create a new instance of `IdentityOperator`, i.e., you allocate memory for it and fill its contents with stuff. The point is that the two instances point to different locations in memory, thus they are not identical.
On the contrary, if you do `op1 = IdentityOperator(space)` and `op2 = op1`, then `op2` points to the same memory as `op1` and the two are identical. What you do with the second command is you *bind the object to which `op1` refers to a new name*. That's fundamentally different from what you do above.

**Comment by kohr-h** [comment]
And @chongchenmath: a perfectly valid question, not at all stupid.

**Comment by chongchenmath** [comment]
Very good explanation @kohr-h . As my understand, the root reason is probably that we have no equality check implementation for `operators` in `ODL`. The following simple example gives us `True` because the `int` class have equality check implementation? 

```python
op1 = 1

op2 = 1

print(op1 == op2)
```

**Comment by kohr-h** [comment]
Yes, and you can observe the same behavior of ODL vector spaces, for instance `DiscreteLp`.

As I said before, for operators it's just too hard to come up with a reasonable equality check since there are so many ways in which two operators can be equal (in the sense that any input will produce the same output). Just take `IdentityOperator`. Here are some ways to generate another operator that should be equal:

- `ScalingOperator(space, 1.0)`
- `ResizeOperator(space, ran_shp=space.shape)`
- `ResamplingOperator(space, space)`
- `FourierTransform(space).inverse * FourierTransform(space)`
- ...

Just too many choices, no way to keep such a system together in a predictable way (for instance, what about tiny numerical errors).

**Comment by chongchenmath** [comment]
Now I understand. Thank you so much @kohr-h

**Comment by adler-j** [comment]
With that said, we could probably add `==` for a whole bounch of operators if we really wanted, the question is if it is worth it. Adding it to some of the obvious ones could perhaps save some user errors, another option is that we explicitly dis-allow it, e.g. add

```
def __eq__(self, other):
    raise NotImplementedError('Equality checking not implemented')
```

**Comment by kohr-h** [comment]
> Adding it to some of the obvious ones could perhaps save some user errors,

I don't really see any really obvious ones. For any level of obviousness we're probably going to miss some "obvious" cases and that would confuse users even more.



> another option is that we explicitly dis-allow it

That's quite harsh and IMO unnecessarily cuts off some valid use cases. For instance any sequence type equality checks where the same instance (e.g. an `IdentityOperator`) can be in multiple sequences.
