### ISSUE TITLE
Add Operator.norm

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#1065]
Computing operator norms happens all the time in code, and we mostly refer to the `odl.power_method_opnorm` method, which is fine but error prone and occationally slow.

I propose that we add a new method called `Operator.norm` with the following default implementation:

```python
def norm(self, estimate=False):
    if not estimate:
        raise NotImplementedError('Operator norm not implemented')
    else:
        return odl.power_method_opnorm(self)
```

Some classes could then over-ride this method when there are known formulae. For example, in `DiagonalOperator` we could implement

```python
def norm(self, estimate=False):
    # Pen-and-paper exercise shows that this holds
    norms = [op.norm(estimate=estimate) for op in self.operators]
    return max(norms)
```

for some other operators I'm sure we could obtain similar bounds.

One obvious issue with this is non-linear operators, so we'd need to solve #551.

**Comment by MatthiasJE** [comment]
I am strongly in favour of this one. As we often estimate the operator norm, it would be good to be able to change the way it is being estimated. So, you may want to estimate the operator norm with your favourite method but still want ODL to use this number. 
Let's say there are operators A and B, A having a closed form operator norm and B not. Then one might want to estimate the norm of B and use that ||A o B|| \leq ||A|| ||B||. However, in a different application one would want to estimate the norm of A o B directly. Thus, one would need to allow to SET the operator norm.

**Comment by kohr-h** [comment]
One problem with this is that the "exact" operator norm depends on the spaces between which the operator is defined. In particular weighted spaces and/or Lebesgue spaces with different exponents make this somewhat more involved. 

For instance, an operator between weighed Lebesgue spaces, `A: Lp(X_w) -> Lq(Y_v)` with weights `w` and `v` has norm (assuming p and q are finite)
```
||A|| = sup{ ||Af||_{Y_v} / ||f||_{X_w} | 0 != f in X}
      = sup{ ||v^{1/q} Af||_Y / ||w^{1/p} f||_X | 0 != f in X}
      = sup{ ||v^{1/q} A(w^{-1/p} f)||_Y / ||f||_X | 0 != f in X}
```
If `v` and `w` are constants, the opnorm between the weighted spaces is simply a constant multiple of the "baseline" norm, with constant `v^{1/q} / w^{1/p}`. Otherwise the norm has to be computed.

So yes, I am also in favor of adding this kind of functionality, but we need some logic to handle weightings, exponents etc. properly. I don't want another property added that disrespects weightings (see #1068).
