### ISSUE TITLE
module 'odl' has no attribute 'uniform_discr'

### ISSUE THREAD

**Issue by cleverzh** [odlgroup/odl#1083]
Traceback (most recent call last):
  File "learned_chambolle_pock.py", line 22, in <module>
    space = odl.uniform_discr([-64, -64], [64, 64], [size, size], dtype='float32')
AttributeError: module 'odl' has no attribute 'uniform_discr'

**Comment by adler-j** [comment]
Hi cleverzh!

It seems this is related to this code: https://github.com/adler-j/learned_primal_dual, right?

Anyway this code works for me:

```python
>>> import odl
>>> size = 128
>>> odl.uniform_discr([-64, -64], [64, 64], [size, size], dtype='float32')
uniform_discr([-64.0, -64.0], [64.0, 64.0], (128, 128), dtype='float32')
```

so it seems you have not installed ODL properly.

In order to run the code in that repository you need to run this branch: [adler-j:tensorflow_support](https://github.com/odlgroup/odl/pull/972).

The easiest way to install that branch is to run `pip install https://github.com/adler-j/odl/archive/tensorflow_support.zip`.

**Comment by cleverzh** [comment]
Thank you very much. I have reinstall the package. Line 22 of "learned_chambolle_pock.py" woks well.

**Comment by cleverzh** [comment]
By the way. The error shows that numpy should be updated to the latest version.

**Comment by adler-j** [comment]
Since this is solved for you, I'll close this issue for now! Thanks for making this known to us.

**Comment by xifeng-lin** [comment]
hello，i have installed odl by pip install https://github.com/adler-j/odl/archive/tensorflow_support.zip and install adler by pip install https://github.com/adler-j/adler/archive/master.zip,but still got this error: module 'odl' has no attribute 'uniform_discr'.
