### ISSUE TITLE
Implement gradient and divergence operator

### ISSUE THREAD

**Issue by moosmann** [odlgroup/odl#109]
For TV-regularization we need a gradient and divergence operator. I'll make a branch with an implementation which is based on `numpy.gradient` and works for arbitrary dimensions. For the moment I'll add it in `./odl/operator/fspace_ops.py`.

**Comment by adler-j** [comment]
For more info on this, see the discussion in #39.

**Comment by kohr-h** [comment]
I guess this is more like the spatial gradient of a discrete function rather than the gradient of a functional. The functionals we have in mind are truly continuous object, and their gradient is supposed to be given in some closed form, based on a pen-and-paper exercise.

This needs to be fit into the discretization framework, however. I'll have a look into it once it's up.

**Comment by adler-j** [comment]
Agree with @kohr, but the terminology needs to be appropriate. There are example implementations of this for cuda available in [odl-examples/CudaTVDenoiseImage.py](https://github.com/odlgroup/odl-examples/blob/master/cudaTVDenoiseImage.py).

An obvious requirement is to also add the adjoint of the gradient. You can also skip implementing the divergence in a first step, since

``` diverge(x) == -gradient.adjoint(gradient(x)) ```

**Comment by moosmann** [comment]
How shall we call it `SpatialGradient`, or simply `Diff`? I will make a preliminary pull request of [branch](https://github.com/odlgroup/odl/tree/issue-109__grad_div) after lunch.

**Comment by kohr-h** [comment]
I suggest `DiscreteGradient`. Your partial derivative helper function may be worth constituting a separate `DiscretePartDeriv` operator. Make a pull request, then we look into the discretization thing.

**Comment by adler-j** [comment]
+1 on `DiscretePartDeriv`, this could be useful.

**Comment by adler-j** [comment]
Now on master.
