### ISSUE TITLE
Unary minus broken

### ISSUE THREAD

**Issue by MJLagerwerf** [odlgroup/odl#1189]
```python
>>> np.sum(-odl.rn(2**31).one())
0.0
>>> np.sum(-odl.rn(2**31-1).one())
-2147483647.0
```

**Comment by kohr-h** [comment]
This is pretty bad, but very likely not our fault.

The `-` operation uses `lincomb(-1, x, 0, out, out)` which in turn calls BLAS `scal` for this case since the conditions for BLAS are fulfilled (contiguous and float32 or float64).
So the most likely reason is that BLAS internally uses 32-bit integers for indexing and overflows for this size.
Here's an isolated test:
```python
def test_scal(size, dtype, factor):
    rn = odl.rn(size, dtype=dtype)
    x = rn.one()
    scal = scipy.linalg.blas.get_blas_funcs('scal', dtype=dtype)
    true_res = np.multiply(x, factor)
    res = scal(factor, x.data, x.size)
    if not np.array_equal(np.asarray(true_res), np.asarray(res)):
        print('NOT EQUAL')
        print('res min / max', np.min(res), np.max(res))
        print('x min / max', np.min(x), np.max(x))
```
This gives me
```python
>>> test_scal(2 ** 31, 'float32', -1)
NOT EQUAL
res min / max 1.0 1.0
x min / max 1.0 1.0
```
and the outcome does not seem to depend on `dtype` or `factor`. In fact, the input seems unchanged after the call which should be in-place.

So it seems we need to work around this by adding 
```python
    and x.size <= np.iinfo('int32').max
```
to [this check](https://github.com/odlgroup/odl/blob/baecb8ada64995b7437cd21590f5a005f5695e9e/odl/space/npy_ntuples.py#L477-L480).

[Here](https://github.com/numpy/numpy/issues/5533) is more evidence.

**Comment by kohr-h** [comment]
Fun fact: if you use a size larger than `2 ** 32`, the integers wrap around past 0, and some array elements are actually mutated since the used size is larger than 0 😁

**Comment by adler-j** [comment]
Interestingly I get a `OverflowError: Python int too large to convert to C long` when running your example on windows, I wonder why you don't.

With that said we obviously need to add a test for arrays of this size.

**Comment by wjp** [comment]
That is probably because a C long is 64 bit on 64 bit Linux, but 32 bit on 64 bit Windows.

**Comment by adler-j** [comment]
> That is probably because a C long is 64 bit on 64 bit Linux, but 32 bit on 64 bit Windows.

sounds very plausible to me. But interesting that there is no error message on linux anyway, scary that anyone in their right mind uses `long` in these days. `int_fast32_t` and those are in general always preferable if speed is an issue, and we get a size guarantee.
