### ISSUE TITLE
PDHG with vector valued step sizes

### ISSUE THREAD

**Issue by mehrhardt** [odlgroup/odl#1327]
I would like to extend the implementation of PDHG (and SPDHG) to vector valued step sizes. For this we need to be able to compute prox operators with vector valued step sizes and to compute pointwise vector products. This issue is related to #904 and #1166.

For scalar valued step sizes, some of the updates read like

`new.lincomb(1, old, tau, update)`
which only works if `tau` is a scalar. What would be the best option to extend this to vector valued `tau`? Should one extend `lincomb` or should one write `new = old  + tau * update` (or similar) instead?

**Comment by sbanert** [comment]
I would distinct the cases with ``np.isscalar(tau)``. If this is true one can proceed with ``lincomb`` (and probably avoid some copying) and otherwise the more general approach is done.

**Comment by mehrhardt** [comment]
Yes, perhaps. Or would it make sense to extend `lincomb` to cover this case? Or write something similar to `lincomb`? @kohr-h, @adler-j, do you have an opinion on this?

**Comment by kohr-h** [comment]
The main purpose of `lincomb` is optimization, since for certain operations like `y <- a*x + y` there are optimized BLAS routines to speed up the code. `lincomb` will look at the scalars and choose the (hopefully) fastest option.
I don't know if there are optimized implementations of `y += a*x` with vector `a`, but in any case I don't want to change `lincomb` for this since it heavily relies on the fact that `a` and `b` are scalars.

The way to go here would be to keep a temporary for the scaled update. You can then always do `update = <something>`, then `update.multiply(tau, out=update)` and then `current += update`.

**Comment by mehrhardt** [comment]
I just checked and BLAS has nothing of the form `vector * vector`, only `diagonal_matrix * vector`.

**Comment by kohr-h** [comment]
As a side note, it may still be a good idea to use a small local function like `axpy_vector` or so, since for GPU it's trivial to generate kernel for that operation (we all hope that CuPy is coming soon), and a function makes the code easier to modify for such a new implementation.
