### ISSUE TITLE
Resizing and resampling

### ISSUE THREAD

**Issue by aringh** [odlgroup/odl#1382]
Assume that I have two spaces, for the sake of argument let them be
```python
space1 = odl.uniform_discr(0, 1, 11)
space2 = odl.uniform_discr(-1, 1.5, 23)
```
Now I would like to take an element in the (function) space `space1` and map it into `space2`. How would one do this in the simplest way on `odl`? I assume I need to use the `ResizingOperator` and the `Resampling` (in that order), however I don't quite get how to do it.

(Zero-padding outside the original domain is fine, and simple linear interpolation for the values in the new discretized points is also ok.)

**Comment by kohr-h** [comment]
This is a nontrivial problem, since we lack information about how to continue the function, and the grids aren't matched either.

One tremendously hacky way of doing it would be this:
```python
>>> space1 = odl.uniform_discr(0, 1, 11)
>>> space2 = odl.uniform_discr(-1, 1.5, 23)
>>> x = space1.element(lambda x: np.exp(-x))
>>> y = space2.element(x.interpolation._call_out_of_place)  # uh-oh, accessing private members :-/
>>> x.show()
>>> y.show()
```
![figure_1](https://user-images.githubusercontent.com/5030250/41765286-ed3f8b52-7603-11e8-823e-852110e763cf.png)
![figure_2](https://user-images.githubusercontent.com/5030250/41765373-28170d5e-7604-11e8-9ab9-c961251cebda.png)

**Comment by aringh** [comment]
Thanks a lot for the input! :smiley: I know it is a non-trivial problem since there is a priori no information on how to extend the function outside the domain. But in some special cases, I a a user might have information about that a zero-order-hold or a zero-padded extension of the function is a good idea.

I do not say that odl should support this natively (because it definitely should NOT), but it is still good to know that I can do it. Even if it is a bit hacky :wink:
