### ISSUE TITLE
RegularGrid.issubgrid ignores as_midp

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#142]
It seems this test does not care about `as_midp`, is this expected?

**Comment by kohr-h** [comment]
Yes. In fact, the `as_midp` thing is sort of a hack to avoid creating a new class like `Partition` or `Tesselation` which represents the subsets rather than the points. The grid is really always interpreted as just the points, except for the functions interacting with `IntervalProd` or emulating its behavior to some degree. It may be too confusing and buggy in the long run, we may want to implement this properly, letting the grids only take care of the points and adding the extra functionality in some layer on top.

**Comment by adler-j** [comment]
I have this feeling that we may want to add the tesselation class at some point. Many issues seem to be popping up.

The issue with voxel volumes of 1 voxel thick systems is also related.

Anyway we now have a as_midp fixture so we at least test both cases.

**Comment by adler-j** [comment]
I'll close this one, but the need for a `Tesselation` could come later, we'll have to keep it in mind.
