### ISSUE TITLE
What is the source of Conjugate Gradient Normal solver

### ISSUE THREAD

**Issue by ginsanity15** [odlgroup/odl#1429]
Dear Developers of ODL,

I am pretty impressed by the outcome of solver: `conjugate_gradient_normal` embedded in ODL. However, may I know what algorithm has you implemented here? I have taken a look at the Wikipedia article mentioned in that function but information in regard to conjugate gradient on normal equation is quite limited there. Based on my limited understanding, I don't think your method is CGLS or LSQR mentioned in that Wiki page. Neither do I think it is a simple extension of standard Conjugate Gradient method (Extending Ax = b to A.T A x = A.T b). 

For this reason, could you please provide some other source about this specific function? I would truly appreciate it if there exists a detailed description of it. 

Cheers,
Bo

**Comment by adler-j** [comment]
This is a great question. I frankly don't have a source right now. I'll try to find one and get back to you!

**Comment by kohr-h** [comment]
The docs are a bit lacking, unfortunately. But if you look at [the source code](https://odlgroup.github.io/odl/_modules/odl/solvers/iterative/iterative.html#conjugate_gradient_normal), you'll see that there are some inline comments that show what's happening. I'll try to relate our notation to the Wikipedia notation.

One thing that's important to understand about CGLS vs. standard CG is that CG assumes a square matrix `A` (i.e. an operator `op` has identical `domain` and `range`), whereas CGLS works for rectangular matrices. If you look at it in a naive way, you can replace the original equation `Ax = y` with the normal equation `A*Ax = A*y` and just feed the new operator `A*A` and the new right-hand side `A*y` into the standard CG algorithm.
Ultimately, that's what's happening, but you can rewrite some of the steps a little bit to make the iteration more efficient.

Here are the steps (I rename `rhs` to `y`)

　                   | ODL                                       | WIkipedia
----------------- | ------------------------------------------ | ----------------------------
Initialization  | 　                                             | 　            
　                 | d = y - Ax                                  | r = b - Ax 
　                 | p = A*d                                     | -              
　                 | s = p                                         | p = r        
Loop            | 　                                              |　            
　                 | q = Ap                                      | -             
　                | a = \|\|s\|\|^2 / \|\|q\|\|^2               | a = <r, r> / <Ap, p>
　                | x = x + ap                                  | x = x + ap
　                | d = d - aAp                                | r = r - aAp
　                | s = A*d                                      | 　             
　               | b = \|\|s_new\|\|^2 / \|\|s_old\|\|^2 | b = <r_new, r_new> / <r_old, r_old>
　               | p = s + bp                                   | p = r + bp

So the main differences are that

1.  `p` has to be a domain variable and thus must be "pulled back" with the adjoint A*,
2. the denominator of the `a` step has the operator A on both sides (since ||q||^2 = <Ap, Ap>), and
3. `b` is computed with the "pulled-back" vectors `s` as well.

**Comment by ginsanity15** [comment]
Thank you so much for this detailed description, I found the comparison table listed by you particularly helpful.

**Comment by adler-j** [comment]
Great that this was resolved! Perhaps we should try to add some of this to the documentation in ODL.

**Comment by kohr-h** [comment]
I'll close this as resolved.
