### ISSUE TITLE
Optimisation algorithm not working properly for my problem

### ISSUE THREAD

**Issue by miallo** [odlgroup/odl#1442]
Hello!

The [minimisation algorithm for my problem / my code](https://github.com/miallo/ODL_Not_Working) is not working as expected. I tried out many different sets of parameters but still it didn't converge (or if it got better, then it took many iterations for marginal changes). I tried out most of the implemented optimisation algorithms but I didn't have any better luck with any of them.
I try to minimise `f(x1, x2) = sum_{i=0}^1 ||abs(FFT(x_i))^2-I_i||_2 + ||Unsupported_Region * x_i||` where x_i are C^2 functions. Right now it doesn't even work with 16x16 pixel simulated data (we will need 2048x2048).

I guess I made a mistake somewhere but even after weeks of (more or less focused) searching I couldn't find anything. Maybe you guys can help me?

Thank you very much in advance,
Michael

**Comment by kohr-h** [comment]
Hi Michael! I tried out your code as far as I got it working with vanilla ODL. One thing you might want to look into is the scaling.
I took the small example and checked the norm of the operator derivative at `one()`: it was about `1600`. Later on I checked the value of the functionals involved in the problem: `sep_sum(sep_sum.domain.one())` yields `5.2e+10`, while `sup_norm(sep_sum.domain.one())` gives `2e+04`. So there might be a significant mismatch between the scales of the components, which would explain the slow convergence.
One way to address the problem would be to scale the problem: for instance, define a new forward operator `new_fwd_op = forwardOperator / np.sqrt(1600)` and new data `new_psiL = psiL / 1600` (same for `psiR`) so that you still solve the same problem but get derivative operators that have about unity norm.

Alternatively, you can just crank up the parameter in front of `sup_norm`, but with values as large as `5e+10` I'd start worrying about numerical stability.

**Comment by miallo** [comment]
Thank you very much! I had to play around a bit with the parameters but now it seems to work.
