### ISSUE TITLE
Trouble installing from source

### ISSUE THREAD

**Issue by zaccharieramzi** [odlgroup/odl#1486]
I use a virtual environment with `python3.5` and I am trying to install `odl` form source using [information from the docs](https://odlgroup.github.io/odl/getting_started/installing_source.html#using-only-pip) (the following example requires a working `virtualenv` and `git`):
```
mkdir tests
cd tests
git clone https://github.com/odlgroup/odl
cd odl
virtualenv -p /usr/bin/python3.5 venv
source venv/bin/activate
pip install -e .
```

However I get the following error (summarized here to the main point):
```python
ImportError: No module named 'numpy'
```

It required me installing the needed packages as listed [here](https://github.com/odlgroup/odl/blob/master/setup.cfg#L40-L44) (`pip install numpy future packaging scipy`) to get it to work. Maybe there is something mixed up with the setup.

**Comment by kohr-h** [comment]
Hi @zaccharieramzi, thanks for reporting. This is a flaw of `setuptools`, which tries to import the module to determine the version before dependencies have been installed, see here: https://github.com/pypa/setuptools/issues/1724

We should update our docs, however, to make the `-e .` installation work again as documented.

**Comment by kohr-h** [comment]
From the answer I got at the referenced issue in the `setuptools` repo, it seems as though the issue lies quite deep and won't be fixed. So we have to come up with something ourselves.
I got a pointer to a [documentation page](https://packaging.python.org/guides/single-sourcing-package-version/) that lists several options for "single-sourcing" version numbers. Most of them are horrible, but the last one with `setuptools_scm` seems interesting. It would only add a *setup* dependency, not a *runtime* one, so I don't think it would be too bad. Looking into it.
