### ISSUE TITLE
module 'odl.tomo.geometry.conebeam' has no attribute 'ConeBeamGeometry'

### ISSUE THREAD

**Issue by cherryandmoon** [odlgroup/odl#1530]
I am new to odl. I have installed the latest odl and try to build a simple cone beam geometry. 

```
import numpy as np
import os, sys
from PIL import Image
import matplotlib.pyplot as plt
import odl
from odl.contrib.tensorflow import as_tensorflow_layer
from tensorflow.examples.tutorials.mnist import input_data
from IPython.display import display, clear_output
import cv2
import random

apart = odl.uniform_partition(0,2*np.pi,59)
dpart = odl.uniform_partition([-1000,-1000],[1000,1000],(2000,2000))
geom = odl.tomo.geometry.conebeam.ConeBeamGeometry(apart, dpart, src_radius=400,det_radius=800,pitch=0)
```

however, i have received the following error message:

module 'odl.tomo.geometry.conebeam' has no attribute 'ConeBeamGeometry'

Any idea of what may go wrong? Thanks.

**Comment by adler-j** [comment]
Hi @cherryandmoon, thanks for the very well stated question. 

You you try using the short form import instead? `odl.tomo.ConeBeamGeometry`

**Comment by cherryandmoon** [comment]
Hi Adler,

Thanks for your quick reply.

Just tried, and similar error message occurred:
AttributeError: module 'odl.tomo' has no attribute 'ConeBeamGeometry'

I am running this code on Python3 platform in Jupyter, I assume this is correct?

Regards,
Wenjuan

**Comment by adler-j** [comment]
This all sounds quite weird to me. Could you post what `dir(odl.tomo)` gives you?

**Comment by cherryandmoon** [comment]
Adler,

See screenshot below:
[cid:image001.png@01D5837A.904AAF00]

Regards,
Wenjuan

**Comment by sbanert** [comment]
Hi. Which version of ODL are you using? The `ConeBeamGeometry` was added quite recently.

**Comment by cherryandmoon** [comment]
Thanks. just checked in the Anaconda, the odl version is 0.7.0. this is the latest one?

**Comment by sbanert** [comment]
The newest version is the master branch of the github repository, and the documentation on [https://odlgroup.github.io/odl](https://odlgroup.github.io/odl) is generated from this branch. In version 0.7.0, there existed a `ConeFlatGeometry` instead of `ConeBeamGeometry` (for the differences between these, I have to refer to @adler-j or @kohr-h, but I guess that the former is restricted to a flat detector). Unfortunately, ODL is still in a pre-1.0 state, so that interface changes might happen.

**Comment by cherryandmoon** [comment]
Dear Sebastian,

Sorry for the late reply. Was out most of time last few days. I think you are right. I have changed the code to ConeFlatGeometry and it seems work. where can I find the spec of this function? I can’t find this in search engine.

Also, do you know how can I get the latest odl with the ConeBeamGeometry?

Thanks.
Wenjuan

**Comment by aringh** [comment]
Hi @cherryandmoon!

At the moment, there is no later release of odl than version 0.7.0. However, to get the latest updates that are currently on the master-branch of the repository, you can clone the repository and install it. To do this, you could for example follow the instructions in the documentation found [here](https://odlgroup.github.io/odl/getting_started/installing_source.html).

Regarding documentation: the goal is that each function should be well-documented. Thus, if you are using a somewhat sophisticated IDE it can normally display this documentation in a nice, formatted fashion (in, e.g., [Spyder](https://www.spyder-ide.org/), by marking the function name and pressing ``crt``+``i``). Otherwise, this is how [ConeFlatGeometry](https://github.com/odlgroup/odl/blob/v0.7.0/odl/tomo/geometry/conebeam.py#L555) looked like in release 0.7.0. There you can find the same documentation, although not as nicely formatted as when using an IDE.

**Comment by adler-j** [comment]
An even easier way is to simply run this in the command line:

```
pip install https://github.com/odlgroup/odl/archive/master.zip
```

I'll see if we can update the instructions with it.

**Comment by cherryandmoon** [comment]
Alex,

Thanks. That’s really helpful.

Regards,
Wenjuan

**Comment by cherryandmoon** [comment]
Jonas,

It works. Many thanks.

Regards,
Wenjaun

**Comment by adler-j** [comment]
Great to hear that it worked, I'll close this then.
