### ISSUE TITLE
Pytorch wrapper

### ISSUE THREAD

**Issue by gmzang** [odlgroup/odl#1537]
Hi team,
When I use torch with ODL as shown here: https://github.com/odlgroup/odl/tree/master/odl/contrib/torch. For example , when typing:  python3  operator_module.py 

there are one issue:

Traceback (most recent call last):
  File "operator_module.py", line 10, in <module>
    import torch
  File "/home/zangg/anaconda3/envs/odl-py35/lib/python3.5/site-packages/torch/__init__.py", line 56, in <module>
    from torch._C import *
ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory

Could you please help to fix this??  it seems the issue is from the different cuda version?? currently i am using python 3.5, cuda10.1, ODL 1.0-dev
Thanks

**Comment by kohr-h** [comment]
Hi @gmzang. It seems that your PyTorch installation is broken, since the error occurs at the `import torch` statement. This has nothing to do with ODL. So I'd suggest you follow the official PyTorch installation documentation. (The error looks like your `torch` wants to import a CUDA 8 library but you have CUDA 10.)
I'll close the issue.
