### ISSUE TITLE
Norm estimate off by 2x and doesn't converge to the right value

### ISSUE THREAD

**Issue by mlubin** [odlgroup/odl#1561]
I found this surprising behavior in the norm estimate computation. The estimates are about a factor of two from the value computed by numpy. Running the power method for more iterations and tighter tolerances does not improve the estimate, which is also surprising because the power method should converge rather quickly. It's quite possible that I've misunderstood something fundamental. Thanks!

## Setup
```py
import numpy as np
import odl
np.random.seed(12)
X = np.random.normal(size=(100,100))
L = odl.MatrixOperator(X)
```
## Unusual behavior
```py
>>> L.norm(estimate=True)
10.00298085568247
>>> np.linalg.norm(X, ord=2)  # The expected value.
19.492578280435232
>>> odl.power_method_opnorm(L, maxiter=2)
10.81398255418922
>>> odl.power_method_opnorm(L, maxiter=1000, atol=1e-12, rtol=0.0)  # More iterations don't help
10.375771243811089
```

**Comment by kohr-h** [comment]
Hi @mlubin. Thanks for the bug report! It's indeed surprising and based on an overlook on our side regarding the relation between operator norm and the result of the power iteration.
The power method converges to the absolute value of the largest *eigenvalue*, whereas the operator norm for p=2 is the largest *singular value*. Those two only coincide if the matrix is *normal*.

What ODL usually does is correct: it applies the power iteration to `A^*A` and takes the square root of the estimated eigenvalue. However, when domain and range of the operator are the same (as in your case), ODL uses `A` directly, which gives the wrong result except for special cases.

So the fix is to simply remove this special case algorithm and always use the one for `A^*A`.
