### ISSUE TITLE
Jenkins shouldnt report PEP8 fails as FAILURE

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#186]
It would be preferable if it gave a more "telling" error message, such as `PEP8-FAILURE` or similar.

**Comment by kohr-h** [comment]
Failing too often, huh? :-)

But I agree. Now Jenkins does the same as Travis, namely run `py.test --pep8`, which results in a hard fail if there is anything wrong. I can try to run the standalone `pep8` utility instead and report those issues separately.

**Comment by adler-j** [comment]
> Failing too often, huh? :-)

*whistles*

Jokes aside, mainly it is more informative for the log to see if it actually failed hard or if it was just a style issue.

**Comment by kohr-h** [comment]
Right. I'll check if I can convince the [Email-ext plugin](https://wiki.jenkins-ci.org/display/JENKINS/Email-ext+plugin) for Jenkins to send out such mails.

**Comment by kohr-h** [comment]
It's not so easy. By default the `BUILD_STATUS` environment variable is used in the title, and it's not possible AFAIK to define new build statuses. So to get around, I would have to write a custom groovy script to look for PEP8 errors and set the email subject in case it finds something but the build has succeeded. I doubt that it's really worth the effort.

In the meanwhile, it's easier to just run `py.test --pep8` "at home" and make sure builds don't fail because of this.

**Comment by adler-j** [comment]
Trying to do that, simply mess up at times. Anyway, how about doing two runs, one usual and one with:

`py.test --pep8 -m pep8`

this only runs pep8.

**Comment by kohr-h** [comment]
Oh god, another build.. Okay, at least simpler than learning a new scripting language :-)

**Comment by kohr-h** [comment]
Done

**Comment by adler-j** [comment]
How does it look now? A truly separate build?

**Comment by kohr-h** [comment]
Yes, the proper builds don't check for PEP8 any longer, and there's an extra `*-pep8` build for master and issues separately. Unfortunately, e-mail reporting does not work exactly as it should, so you probably didn't get a mail. I think I'll switch to unconditional mails to everybody in the meanwhile.
