### ISSUE TITLE
RegularGrid.points() not compatible with vectorization

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#197]
Currently the following happens:

```python
>>> X = odl.FunctionSpace(odl.Rectangle([0, 0], [1, 1]))
>>> f = X.element(lambda x : x[0]**2 + x[1]**2)
>>> points = odl.uniform_sampling(X.domain, [100, 100]).points()
>>> f(points)
TypeError: argument array([[ 0.005,  0.005],
       [ 0.005,  0.015],
       [ 0.005,  0.025],
       ..., 
       [ 0.995,  0.975],
       [ 0.995,  0.985],
       [ 0.995,  0.995]]) not a valid vectorized input. Expected an element of the domain [0.0, 1.0] x [0.0, 1.0], a (2, n) array or a length-2 meshgrid sequence.
>>> points.shape
(10000L, 2L)
```

it seems to me these points should be flipped.

**Comment by kohr-h** [comment]
That's right. The problem is that there are two viewpoints, namely an *array of points* where one expects `for p in points` to do the right thing and give one point at a time, and on the other hand, functions which need to access one *component array* at a time, i.e. `pts[0]` should be all first components, etc. I don't see a good way to reconcile this other than telling users to plug in `grid.points().T` as function argument. The only way out would be to optionally return points as columns rather than rows.

BTW, `meshgrid` is the way to go anyway :-)

**Comment by kohr-h** [comment]
This is settled, right?

**Comment by adler-j** [comment]
Sure is.
