### ISSUE TITLE
Convention for axis labelling in 3D

### ISSUE THREAD

**Issue by moosmann** [odlgroup/odl#208]
PyASTRA, Stir, and numpy use the convention that the slowest changing axis comes first: (z, y, x). Should we adopt to this convention as well and make the rotation about the first axis the default?

**Comment by adler-j** [comment]
I think so, yes.

**Comment by kohr-h** [comment]
Well, the question is not so much which index is slow and which one is fast. That's pretty much defined by the data representation and the ordering of the discretized space. The question is rather which spatial axis we identify with which index, and you're arguing for using the convention `x <-> fastest`, ..., `z <-> slowest`. In that sense, Numpy does not have an axis convention, just a default data ordering.

I think we need a good reason *not* to assign `x <-> index 0`, ..., `z <-> index d-1` since that would be the most obvious thing. If efficiency of common slicing operations (which is probably `z = const.`) is the main issue, we could still default to Fortran ordering. I'm not sure about performance implications and broad support in Numpy, but this should not be that big of an issue. If *everybody* else does it your proposed way, fine. But I'm not yet convinced.

**Comment by moosmann** [comment]
Ok. Since there is not a unique way for assigning x,y,z to axis indices and it often leads to confusion, why don't we refrain from using x,y,z at all and simply use axis 0,1,2 everywhere?
