### ISSUE TITLE
Bad error message for e.g. addition of elements from different spaces

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#271]
This is what happens currently:
```python
>>> discr1 = odl.uniform_discr(0, 1, 10)
>>> discr2 = odl.uniform_discr(0, 1, 11)
>>> discr1.one() - discr2.one()
Traceback (most recent call last):
...
TypeError: unsupported operand type(s) for -: 'DiscreteLpVector' and 'DiscreteLpVector'
```
For users unfamiliar with ODL, this is quite devastating since it's obviously wrong and gives no clue how to fix it.

The problem is that we return `NotImplemented` in all situations we cannot do anything. But aren't there situations where we can be sure that the operation will never make sense and we should say exactly why?

If there is no way to reliably fix this behavior, we definitely need an FAQ entry.

**Comment by adler-j** [comment]
Well the culprit is [here](https://github.com/odlgroup/odl/blob/c57bac6e76b9c0e2805f0bba2ea9350cea6a36c1/odl/set/space.py#L517-L533), it is quite hard to solve, basically we would need to change the line:

```python
if other in self.space:
```

to something like

```python
if other in self.space:
    ...
if other "almost in" self.space:
    raise ValueError(...)
```

Simply changing the last line from `NotImplemented` to `ValueError` is not "pythonic" I think.

**Comment by kohr-h** [comment]
Yes, that's not a nice thing to do. Probably we need to go with the FAQ solution.
