### ISSUE TITLE
Unclear meaning of starting angle in geometries

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#295]
From the discussion on the `issue-87__conebeam` branch:

> We're not clear on how we interpret the initial positions / vectors / axes. Are they associated
>     with the _start value_ of the angles, i.e. `angles=motion_params.begin` or with `angles=0`?
>     The current implementation does the latter, which I think is debatable. What is more practical?
>     If one wants to use an angle interval of `[-pi/2, pi/2]`, is it better to have the user give the state
>     of the geometry at angle 0 or at `-pi/2`? This seems to depend on the application.

Not exactly sure what would be the best. We could default to `motion_params.begin` and allow users to specify a point-value pair if the value at a different point shall be fixed. Would add some complexity though, since we would need to store both.

**Comment by adler-j** [comment]
I feel that the current system is the only logical solution. In any application, you will in general have a fixed "reference position" of your system which defines the coordinate system. Typically this can be straight up, or down. In this case, we can give the initial detector axes etc in this system (by defining it as angle=0). This way, you can typically let the detector axes be [1, 0, 0] and [0, 1, 0], or something equally trivial. If we were to change this to be given by `angles.begin`, users would need to recalculate the detector position for each new data set.

Since this is basically the only use case for these options (anyone working with artificial data might as well go for the defaults in 99% of cases), changing would add work to users at debatable gain.

**Comment by kohr-h** [comment]
> I feel that the current system is the only logical solution. In any application, you will in general have a fixed "reference position" of your system which defines the coordinate system.

Correct, so then we should not use "init" in the names but rather something like "ref" since it's a (somewhat arbitrary) reference point or system of axes. And the docstrings don't say a word about this, they should be much clearer since it's a crucial distinction.

**Comment by adler-j** [comment]
I agree, `ref` would be a nice name for these, and the doc needs some help.

**Comment by kohr-h** [comment]
This is still relevant, and connected to #784.

**Comment by adler-j** [comment]
The mother of these issues is #183, which really needs to be solved.

**Comment by adler-j** [comment]
Was this fixed by #968?

**Comment by kohr-h** [comment]
This is settled now for `angle=0` as the reference.
