### ISSUE TITLE
Derivative test needs some rethinking

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#334]
Our current derivative test computes

    ||A(x + c*p) - A(x) - c * A'(x)(p)|| / (|c| * ||p|| * ||A||)

and produces an error if this quantity is larger than 0.00001.

There are a couple of issues with that:

1. The test requires the specification of an estimate of the operator norm `||A||`, but that is hard to get for non-linear operators which one usually has in this test.
2. If the tested operator is differentiable and the implementation of its derivative is correct, then

        ||A(x + c*p) - A(x) - c * A'(x)(p)|| = o(c ||p||)

    i.e. the linearisation error drops asymptotically super-linearly. If the operator is twice continuously differentiable, the convergence is quadratic. However, the constant is basically unknown - it would be smaller than the norm of the second derivative `||A''||` times `||p||^2`, but who knows how to compute that first guy..
Anyway, the point is that normalizing by `1 / ||p||` and an operator norm and requiring the resulting relative error to be small is somewhat arbitrary. Also, if the convergence is only slightly faster than linear, reaching the required threshold would be hard even for correctly implemented derivatives.
3. Finally, at least for some types of operators, there is a sort of "saturation" effect. For example, with the deformation operator we're currently implementing, a very small disturbance of the deformation parameters (smaller than the sampling grid step) will have no effect, hence the first term

        A(x + c*p) - A(x)

   will be *exactly* zero for all `c` below a certain threshold (grid step if `p` is about unit length), hence the error term is *exactly*

        |c| * ||A'(x)(p)||

   i.e. one will observe exactly linear asymptotic behaviour, not super-linear. I suspect that all kinds of "domain manipulation" operators will behave like that.

#### What to do about that

I don't exactly know. Perhaps we can try to observe the asymptotic by testing a couple of `c` values of different scales and print the error together with its measured convergence rate.

**Comment by adler-j** [comment]
1. Agree that this is an issue.
2. This is obviously related to the first issue in that the normalization is there to make sure that the error is "appropriately small".
3. In this case, I think that the test is actually correct and the operator is wrong. The operator is obviously not differentiable as currently implemented, something that the diagnostics is pointing out.

##### What to do

Well a obvious solution to 1/2 would be to drop all normalization and simply verify the o(c) relation.

Basically:

```
step = initial_step  # like 1
while step > eps:
    if ||A(x + c*p) - A(x) - c * A'(x)(p)||/c < threshhold:
        return derivative_ok
    else:
        step /= 2
return derivative_bad
```

Regarding 3 there is no ok solution that wont appear wierd in some cases. I think we should leave this as is and simply accept that that operator is not differentiable, the diagonstics are simply a guideline anyway (but if you get a bug at some point, you now know that it may be because your derivative is wrong).

**Comment by adler-j** [comment]
Some other thinking on derivatives by another library can be found here:

https://github.com/ampl/mp/blob/686443b36777b6f672917aafcdad540ac95ad4fd/test/function.h#L763-L796

It seems he does smaller steps and uses that the central difference converges faster than the forward difference and hence we should have something like

||(A(x + c*p) - A(x - c*p))/2 - c * A'(x)(p)|| = o(||A(x + c*p) - A(x) - c * A'(x)(p)||)

from which the scalings are automatically eliminated.

**Comment by kohr-h** [comment]
Hm, I have a hard time seeing that that is what happens in the linked code. Whatever. For central differences to be of quadratic order, one needs twice differentiable `A`. Apart from that, I don't see the big advantage over the asymptotic test with forward differences only, like
```
c = initial_step  # like 1
old_err = 1
while c > eps:
    err = ||A(x + c*p) - A(x) - c * A'(x)(p)||
    if err / old_err < 0.5:
        return derivative_ok
    else:
        old_err = r
        c /= 2
return derivative_bad
```
Or simply the same with `c = 2*eps` and `c=eps` and check the error drop. Or require consistent error drop for at least a couple of c values.

**Comment by adler-j** [comment]
The problem with your test is that we get asymtotically close if we use a "wrong derivative", for example, if you multiply your derivative by 2, the error goes asymtotically to 0.5 (from above, but what would we know about numerical errors). We also cannot set the value to lower than 0.5, since that is the only thing guaranteed by the theory.

Quite frankly, verifying the correctness of a derivative if the operator is only once derivable is going to be a huge problem, since the error term can decrease arbitrarily slowly. I therefore propose that we assume twice differentiable and assume a O(p^2) error term. We can document for the chance that the operator is only once differentiable.
