### ISSUE TITLE
Resurrect Functional class or extend Operator

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#39]
After the discussions we had about functionals and the properties they have in the light of (convex) optimization, the question is how to solve this in code. I'll make a quick list of what is needed, feel free to edit:

Suppose `phi:X --> R` is a functional, `x in X`  

- `grad phi(x)` = element in `X`. This is special to Hilbert spaces - in Banach spaces it *can be identified with, but is not equal to*, a dual space element. Implementation-wise, `gradient` will probably be an `Operator` from the functional domain to itself.
- Hessian `H_phi(x)` = linear functional `X --> R`. Here it becomes more interesting: should it be something bi-linear `(x, y) --> H_phi(x, y) in R` or rather an `Operator` mapping a domain element to a linear functional?
**Update:** probably better to regard it as the derivative of the derivative.
- Fenchel conjugate `phi*` = functional `X* --> R`. We need to know that `phi` maps to `R`. This can also be defined on general Banach spaces, probably harder to find closed forms though. Unless we introduce the notion of a dual space, we can only support Hilbert spaces (or maybe a few other cases where the dual can be identified with a simpler space, e.g. (L^p)* ~ L^q).
- Lagrange (Fenchel-Lagrange?) conjugate `phi^` = functional in `X`?
- Bregman distance?

The fact that we need the real numbers as range would cause slight headaches in the current `Operator` framework, and most definitions only seem to be relevant for functionals. So I don't really think it makes sense to add this stuff to the `Operator` class. Better to make a subclass which gets these additional attributes.

**Comment by aringh** [comment]
I agree with the subclassing. This is rather special, for use (at least mainly) in optimization.

Regarding the duals, both Fenchel conjugate and Lagrangian dual actually depends on the constraint set you are looking at.
* The Fenchel conjugate is defined as `sup <x, x*> - f(x)`, where the sup is taken over `x` in `C` (`C` = the set of constraints in the optimization problem). The conjugate is then defined over the set `C*`, which is basically all `x*` that makes the sup finite.
* Regarding the Lagrangian dual; it is not one specific dual problem, you get a family of problems depending on which constraints you relax.

**Comment by kohr-h** [comment]
Okay, so I gave the definition for `C = X` and `f` convex right?

Regarding Lagrangian, we probably need to take a closer look as to how to handle different cases, and in general, how to encode constraints. All that without getting overly complex, we're not aiming for a full-fledged optimization package.

**Comment by kohr-h** [comment]
And @aringh you write "nice" links as `[link text](link target)`.

**Comment by adler-j** [comment]
I'll add some comments from what I posted in an earlier pull request on gradients and derivatives that is obviously relevant here.

Suppose we have a `Operator` (or `Functional`) `F`. I'll use the following example here

```python
class F(odl.Operator):
    def __init__(self, x):
        super().__init__(domain=odl.Rn(2), range=odl.RealNumbers())

    def _call(self, x):
        return x[0]**3 + x[1]**3
```
    
I'll try to investigate what the `gradient` and `derivative` of this would be, as well as higher order versions
    
Gradient
--------
We could define the gradient of `F : X --> R`, and mathematically it is the function `F.gradient : X --> X` such that (with an example)

```python
def F.gradient(x):
    return x.space.element([3 * x[0]**2, 3 * x[1]**2])
```

Derivative
----------
Technically the derivative is defined as `F.derivative : X --> L(X, R)`, in this case it could be implemented as

```python
def F.derivative(x):
    class FDeriv(odl.Operator):
        def __init__(self, x):
            self.grad = x.space.element([3 * x[0]**2, 3 * x[1]**2])
            super().__init__(x.space, x.space, linear=True)
            
        def _call(self, y):
            return self.grad.inner(y)
            
    return FDeriv(x)
```

It's also trivial to define it using our `Vector.T` syntax and `F.gradient`

```python
def F.derivative(x):            
    return F.gradient(x).T
```

Second derivative
-----------------

Taking the second derivative is doable in four ways, which we may identify with different concepts

```python
F.gradient.gradient         # Hessian
F.derivative.gradient       # Doesnt realy make sense to me
F.gradient.derivative       # Not quite sure of the name here
F.derivative.derivative     # Second frechet derivative
```
    
* `F.gradient.gradient : X --> X^2` (somewhat unrigorously) as

    ```python
    def F.gradient.gradient(x):
        return [[6 * x[0], 0],
                [0, 6 * x[1]]]
    ```


* `F.derivative.gradient` is undefined since `L(X, X)` is not a inner produt space.

* `F.gradient.derivative : X --> L(X, X)` is simple to define (rigorously this time)
        
    ```python       
    def F.gradient.derivative(x):
        return MatVecOperator([[6 * x[0], 0],
                               [0, 6 * x[1]]])
    ```

* `F.derivative.derivative` can be defined in two ways, either as `X -> L(X, L(X, R))` which gives
                
    ```python               
    def F.derivative.derivative(x):
        class Fsecondderiv(odl.Operator):
            def __init__(self, x):
                self.x = x
                ran = LinearFunctionalSpace(x.space)
                super().__init__(self, x.space, ran, linear=True)
                
            def _call(self, y):
                vec = y.space.element([6 * self.x[0] * y[0], 
                                       6 * self.x[1] * y[1]])
                return vec.T
                
        return Fsecondderiv(x)
    ```

    which is obviously somewhat complicated (and even harder to implement if `F` is not "diagonal").

    Another way to think of `F.derivative.derivative` is (less rigorous since it is no longer strictly the derivative of the derivative, but possibly easier to think about) `X -> L(X x X, R)`

    ```python               
    def F.derivative.derivative(x):
        class Fsecondderiv(odl.Operator):
            def __init__(self, x):
                super().__init__(self, 
                                 ProductSpace(x.space, 2), 
                                 x.space.field, 
                                 linear=True)
                
            def _call(self, y):
                return 6 * self.x[0] * y[0][0] + 6 * self.x[1] * y[1][1]
                
        return Fsecondderiv(x)
    ```

Conclusions
-----------

Obviously this is not trivial to think about, and we should maybe give "nice" names for some of the more common operators. 

* For example my second alternative for `F.derivative.derivative` could be called `secondderivative` to differentiate it from `derivative.derivative`, which i.m.o. should follow the definition. 

* Likewise, we could make `F.hessian` instead of `F.gradient.gradient`. This still gives us the question on how we should represent matrices (if at all?)

* For general functions, we could maybe add `F.jacobian` which is a matrix?

**Comment by adler-j** [comment]
Tagging @ozanoktem since this is a quite important discussion.

**Comment by kohr-h** [comment]
We need to keep discretizations in mind, and think about which concepts make sense in general Hilbert (or even Banach) spaces. Let's again say that `f: S --> F` is a functional, where `S` is a vector space over the field `F`.

- The gradient `grad f(x)` is the element in `S` representing the linear functional `f'(x): S -- > R`, i.e. the unique element `g in S` such that `f'(x)(y) = <y, g>` for each `y in S`. This makes sense in any *Hilbert* space due to the Riesz representation theorem.
- For the second derivative, I don't know how to create an analogon. One could interpret the second derivative as a mapping `f''(x): S x S --> R`, but that one is *bilinear* and not *linear*, so there is no way to represent this by an element in `S x S`. So here, there is no element in `S x S` representing the second derivative.

  I think that in general, it only makes sense to speak about the derivative of the gradient and the derivative of the derivative. Both approaches are perfectly doable if the gradient is an `Operator`.
- It may make sense to add some extra structure if the domain of a functional is `Rn`. Here one can have Jacobian and Hessian, perhaps some more stuff restricted to the finite-dimensional case.

**Comment by adler-j** [comment]
This is duplicate, do we close it?

**Comment by kohr-h** [comment]
Yes, we still have it as a reference.
