### ISSUE TITLE
ProductSpaceOperator checks for product spaces in domain and range, why?

### ISSUE THREAD

**Issue by aringh** [odlgroup/odl#403]
As the title says. My question arise because this gives rise to unexpected/unwanted behavior. In the following example
```
import odl

r3 = odl.Rn(3)
r6 = odl.ProductSpace(r3, 2)

I = odl.IdentityOperator(r3)

op_1 = odl.ProductSpaceOperator([I, I])
op_2 = odl.ProductSpaceOperator([I, I], dom=r6, ran=r3)
```
```op_1``` will go through, and maps R^6 to R^3. This should be the same operator as ```op_2```, but here it get an error: ```TypeError: space Rn(3) not a ProductSpace instance.``` Is there a reason for the difference?

(Similarly apply for switching domain and range).

**Comment by adler-j** [comment]
`dom` and `ran` (which should btw be renamed to `domain` and `range` since this is our standard notation), mean the domain and range of the operator, as given in the documentation:

```python
dom : `ProductSpace`, optional
    Domain of the operator. If not provided, it is tried to be
    inferred from the operators. This requires each **column**
    to contain at least one operator.
```

The only usecase of the `dom`/`ran` parameters is in case you want to provide an operator on the form

```python
dom = odl.ProductSpace(I.domain, I.domain, I.domain)
op = odl.ProductSpaceOperator([I, 0, I], dom=dom)
```

since in this case the operator cannot infer what the domain of the second argument should be. Perhaps the documentation should be more clear in this regard.

In your case, the domain and range of the operator are both product spaces:

```python
>>> op_1.domain
ProductSpace(Rn(3), 2)
>>> op_1.range
ProductSpace(Rn(3), 1)
```

If you want a non-productspace domain, you should use `BroadcastOperator`, `ReductionOperator` or `DiagonalOperator`.
