### ISSUE TITLE
Add a padding operator

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#411]
We should allow other options than zero-padding. See #355.

**Comment by kohr-h** [comment]
I'm not completely convinced that we should bake boundary behavior into the Fourier transform directly since the back-end does not natively support it. The preferred way to do this is to compose with a padding operator and its inverse. If we really want it to be part of the operator, one possibility would be to factor out the code from the padding operators and make use of it in the FT.

**Comment by adler-j** [comment]
Changed name of issue to reflect new purpose.
