### ISSUE TITLE
Different notions for domain corners

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#452]
We have a mismatch in names for the minimum and maximum corners of rectangular domains between partitions and discretizations, especially in `uniform_partition` and `uniform_discr`. One uses `begin, end` the other `min_corner, end_corner`. We should find a solution to harmonize these notions, and it should propagate all the way down to `IntervalProd`.

Things to harmonize:
- [x] `min_corner, max_corner`, `begin, end` --> `min_pt, max_pt`
- [x] `nsamples`, `num_nodes` --> `shape`
- [x] `center`, `midpoint` --> `mid_pt`

Edit 2: TODO list added
Edit 3: TODO list modified according to result of discussion & Edit 1 deleted.

**Comment by kohr-h** [comment]
Since `uniform_discr` is probably the most heavily used function, we should consider using its notation. However, I think `nsamples` is not so great, `shape` is more "standard" at least for NumPy users.

**Comment by adler-j** [comment]
I think `shape` is the obvious name instead of `nsamples` (especially since we expose it under the name `samples` already.)

Regarding `begin` vs `min_corner`, some inspiration is:

* [arange](http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.arange.html): `start`/`stop`
* [linspace](http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.linspace.html#numpy.linspace): `start`/`stop`
* [Dolfin, RectangleMesh](https://github.com/FEniCS/dolfin/blob/fcf70d934d63168e5ed037678e22ac66fb2b3474/dolfin/generation/RectangleMesh.h)     
```
    ///     p0 (_Point_)
    ///         First point.
    ///     p1 (_Point_)
    ///         Second point.
    ///     nx (double)
    ///         Number of cells in :math:`x`-direction.
    ///     ny (double)
    ///         Number of cells in :math:`y`-direction.
```

Couldnt really find more. My opinion is that `begin`/`end` is perhaps the easiest to write and quite simple to understand. `min_corner` is perhaps a bit more clean, but too verbose for my taste.

**Comment by adler-j** [comment]
Another note: We have the exact same issue when comparing `center` with `midpoint`, that guy should also be standardized.

**Comment by kohr-h** [comment]
I realized the same thing these days when skimming through the code of `grid.py`.

**Comment by adler-j** [comment]
Was thinking some about this one, and I think that it would be best to go for `min_point`, `shape` and `mid_point`. These are all very clear and can be standardized across various classes.

Using `begin` doesn't make much sense in for example `DiscreteLp`.

**Comment by kohr-h** [comment]
Will take care of this now.
