### ISSUE TITLE
Interface for utility functions for handeling convex conjugate functionals

### ISSUE THREAD

**Issue by aringh** [odlgroup/odl#459]
I'm currently trying to implement some rules for convex conjugate functions, which can be found [here](http://ieeexplore.ieee.org/xpl/articleDetails.jsp?arnumber=7298566), for example given ```f^*(y)``` one can find an expression for the convex conjugate function of the translated function ```(f(. - z))^*(y)```.

These are suppose to be helper-functions, used mainly together with the ```Functional``` class that is also being developed. For example we gets some kind of algebra-like operations: if we have a functional ```f``` and are now interested in ```f(. - z)``` we can automatically compute the new functional, including derivative, gradient, proximal operator and convex conjugate.

In light of this, what is the best interface for the helper-functions? Right now I'm writing them on the form
```
def convex_conjugate_translation(convex_conj_f, y):
    """Calculate the convex conjugate functional of the translated function
    F(x - y).

    This is calculated according to the rule

        (F( . - y))^* (x) = F^*(x) + <y, x>

    where ``y`` is the translation of the argument.

    Parameters
    ----------
    convex_conj_f : `Functional`
        Function corresponding to F^*.

    y : Element in domain of F^*.

    Returns
    -------
    ConvexConjugateTranslation : `Functional`
        Functional corresponding to (F( . - y))^*
"""
```
however I'm not sure of if we want to take functional ```convex_conj_f``` or the functional ```f``` itself as input. What do you think is the most convenient and transparent way? Or is there some other good way of doing it?

**Comment by adler-j** [comment]
Right now this function is equivalent to the one-liner

```python
result = convex_conj_f + y.T
```

In general functions that try to do two things at once is a bad idea, instead the interesting use-case for a user would i.m.o. being able to write something like

```python
# F functional.  y vector
result = translation(F, y).convex_conj
```

or if we go for the functional approach

```python
result = convex_conj(translation(F, y))
```

**Comment by aringh** [comment]
I think we are trying to achieve the same thing... at least I'm not sure of what the difference is. I also want to be able to do: given functional ```f```, compute the convex conjugate of ```f(. - y)```. But maybe you have another approach in mind than what I outline above...?

The use-case I see is, e.g., if I have a functional ```f``` that I have implemented and now I want to instead consider ```f(. - y)```, I don't have to recompute all the elements such as convex conjugate, proximal operator, or even proximal operator of the convex conjugate. Because in this case is also that one can in fact compute the proximal of the convex conjugate of ```f(. - y)```, as this one falls under the "quadratic perturbation"-case.

**Comment by adler-j** [comment]
the difference in approach is that I think it would be preferable, if at all possible, to have each function do only one thing. In this case, you have a function doing two things. If we are to have a specific function for every combination of operations, we would end up with extremely many functions:

* `translation`
* `convex_conjugate`
* `convex_conjugate_translation`
* `translation_convex_conjugate`

etc.

Implementing only a subset of convex conjugate, proximal etc should be fine, as I assume these will default to `NotImplemented`?

**Comment by kohr-h** [comment]
Another approach, [more in line with what we did in the case of `Operator`](https://github.com/odlgroup/odl/blob/3543720d91841c602bfebf94bdbe26986a6f3718/odl/operator/operator.py#L1128-L1136), is to create expression classes which delay the evaluation of the functional(s). It's a poor man's version of a computational graph :-)
Actually, in the functional branch, there is already a `FunctionalComp` class, so in my view it would be natural to extend along the same lines in the case of translation, for example. A hacky implementation could look like this:
```python
class FunctionalTranslation(Functional):
    def __init__(self, func, shift):
        self.functional = func
        self.shift = shift

    @property
    def convex_conj(self):
        return self.functional.convex_conj + shift.T
     
    def proximal(tau):
        # Apply the proximal rule for translation
```
One problem (not only) with this implementation is that `tf = FunctionalTranslation(f, y)` does not know how to compute `tf.convex_conj.proximal(tau)` since there is no rule to add a `Functional` and an `InnerProductOperator`. This would require a `FunctionalSum` class that implements a rule like "if the other guy is an inner product with something, do this". In principle, this is covered by the "proximal of a quadratic disturbance" rule, but this rule must be explicitly applied. Do you see where this is heading :-)?

BTW: This work is highly connected to the functional branch. You should consider working on the same branch and sync your work (or do you already do that?).

**Comment by adler-j** [comment]
```
class FunctionalTranslation(Functional):
    def __init__(self, func, shift):
        self.functional = func
        self.shift = shift

    @property
    def convex_conj(self):
        return FunctionalTranslationCConj(self.functional.convex_conj, shift)

    def proximal(tau):
        # Apply the proximal rule for translation
        
class FunctionalTranslationCConj(OperatorSum):
    def __init__(self, functionalcc, vector):
        super().__init__(functional, vector.T)

    @property
    def proximal(self):
        # computations goes here
```

**Comment by kohr-h** [comment]
Sure, but the issue with the application of the "obvious" rule to `func + v.T` remains unsolved. And at the end of the day, the second guy should subclass `FunctionalSum`, which would in turn require handling an argument of type `InnerProductOperator` (or `InnerProductFunctional` for that part :-) ).

**Comment by adler-j** [comment]
> Sure, but the issue with the application of the "obvious" rule to func + v.T remains unsolved

I'm quite sure this will remain unsolved, there are no general rules that we can implement.

>  And at the end of the day, the second guy should subclass `FunctionalSum`, which would in turn require handling an argument of type `InnerProductOperator` (or `InnerProductFunctional` for that part :-) ).

Not quite sure I follow, those parts of the `FunctionalSum` should be trivial to implement, and require no info about `InnerProductFunctional`, no?

**Comment by kohr-h** [comment]
> I'm quite sure this will remain unsolved, there are no general rules that we can implement.

Why not? You know how conjugate and proximal look like for a (up to) quadratic disturbance, no?

> Not quite sure I follow, those parts of the FunctionalSum should be trivial to implement, and require no info about InnerProductFunctional, no?

See above, I'm thinking conjugate and proximal here, which are in some sense known.

**Comment by adler-j** [comment]
> Why not? You know how conjugate and proximal look like for a (up to) quadratic disturbance, no?

Well sure, if someone wants to sit down and write code (and tests) for each special case then we can do it, I'm just guessing it will be quite cumbersome.

> See above, I'm thinking conjugate and proximal here, which are in some sense known.

Sure, if we want to introduce knowledge of other operators into the operators then sure, but this would make extending ODL with new operators next to impossible. In that case we really need to consider what happens if a user adds a new operator in some external package. How does he make his operator work smoothly with ODL without requiring a merge into the core package?

**Comment by adler-j** [comment]
I suppose this is settled for now and we have agreed on how to do this, as per the branch?

**Comment by kohr-h** [comment]
Agree, this is no longer an issue.
