### ISSUE TITLE
Differentiate between private and protected variables

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#466]
A private variable is a variable that no other class should ever be accessing. These should, according to [PEP8](https://www.python.org/dev/peps/pep-0008/#designing-for-inheritance), be named with double underscores: `__private_variable`.

Protected variables are variables that should not be accessed by external classes, but that are acceptable to access for sub-classes. Examples in odl include `_lincomb` and `_inner`.

We currently do not distinguish between these in a proper maner, which has caused some code where we access seemingly private variables where we shouldn't. This can cause quite some problems in maintenance later on.

My suggestion is that we make all variables that have not been designed for inheritance private. If we find that external classes need to somehow access them, we either upgrade them to protected or public, or we make a property, depending on circumstances.

**Comment by kohr-h** [comment]
I'm all good with this proposal. One important side remark regarding underscored and double-underscored variables is that the latter are "name-mangled" internally, so they *really are* private, unless you're desperate (see also [here](https://docs.python.org/3/tutorial/classes.html#private-variables)).

Consider this code:
```python
class A(object):
    _protected = '(protected) A'
    __private = '(private) A'

    def print_protected(self):
        print(self._protected)

    def print_private(self):
        print(self.__private)
        
class B(A):
    _protected = '(protected) B'
    __private = '(private) B'
```
You get the following behavior:
```python    
>>> a = A()
>>> a.print_protected()
(protected) A
>>> a.print_private()
(private) A

>>> b = B()
>>> b.print_protected()
(protected) B
>>> b.print_private()
(private) A
```
This can be surprising at first sight, but is intentional. Double underscore variable are truly *specific to a certain class* and cannot be overridden in the way shown above.
What happens internally is that the name `__private` is mangled to `_<class name>__private`, i.e. in fact, an instance of `B` will have both `_A__private` and `_B__private`, where the latter is the one that we "overrode":
```python
>>> b._A__private
'(private) A'
>>> b._B__private
'(private) B'
```
Hence, if one is really desperate, one needs to manually replace `_A__private` to change the behavior of the corresponding print function in the example. But there are so many flashing warning lights on the way that hopefully nobody will ever do this. And with multiple inheritance, it may actually be very hard to find out where exactly a variable was defined and manually mangle the name.

**Comment by adler-j** [comment]
This has largely been settled.
