### ISSUE TITLE
pytest 3.0, new features and breaking changes

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#515]
[Pytest 3.0 has been released](http://blog.pytest.org/2016/whats-new-in-pytest-30/), notable changes that affect us include:
- [ ] entry point `py.test` changed to `pytest`, we need to update doc wherever needed
- [ ] `approx` function added, this should supersede many of our usages of `approximately_equal` etc. Basically all of them. `all_approximately_equal` may stay for a while since it is quite heavily optimized.
- [x] `doctest_namespace` added. We can use it to close #410 basically instantly.
- [x] `yield` tests are deprecated and need to be removed.

I assume we should update our pytest dependency to 3.0 rather soon. Perhaps in time for the 0.5.0 patch since this is breaking changes?

**Comment by kohr-h** [comment]
These are really good news, a bunch of things we definitely want to have. On Anaconda, 3.0 is not yet available, but I guess that's only a matter of days. It's on PyPI already.
Not sure if we need a 0.5.0 release though. There are no breaking changes from the users' perspective. On the other hand, we need to update the dependency list, so that's a clear reason for a minor release. Would be okay with me, anyway.

**Comment by adler-j** [comment]
This is done
