### ISSUE TITLE
Add ufunc operators

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#567]
We need operators `X -> X` that apply a ufunc, something like

```
>>> x = odl.vector([1., -2., 3.])
>>> abs_operator = odl.ufunc_ops.abs(x.space)
>>> abs_operator(x)
rn(3).element([1., 2., 3.])
```

**Comment by adler-j** [comment]
Some open design questions that we need to address before adding this:

* Should we name the classes with capital letters? i.e. `ufunc_ops.abs` vs `ufunc_ops.Abs`. The second follows the naming style by being a class, while the first one follows numpy and may thus be easier for users. I say we go for capital first letter.

* Where should the ufuncs be accessed from? Options:
    * Let users access them in the top layer (`odl.Abs`). I vote against this due to clutter and possible collisions.
    * Make them properties of the space, similar to vectors. I.e. `space.ufunc.abs(x) == x.ufunc.abs()`. I'm against this as well since we have so far not made operators that tightly coupled with the space, and I think this may make extension hard. But it is certainly an option.
    * Create a new package like `odl.ufunc_ops`, `odl.ufuncs` or w/e. Users call e.g. `odl.ufuncs.Abs(space)(x)`. I think this is the most clean solution.
    
* How will we handle things like derivatives? I'm guessing all of these will boil down to a `MultiplyOperator`, but how to chose it and how do we specify what is the derivative of what? e.g. `odl.ufuncs.sin(space).derivative(p)(x) == odl.ufuncs.cos(space)(p) * x`, but unless we manually write the ~30 or so ufunc classes adding all of these in a nice manner will be hard.

* How do we handle things with several input/output? e.g. `add(x, y)`? Do we make the domain a productspace? e.g. `odl.ufuncs.add(space)([x, y]) == x + y`.

**Comment by kohr-h** [comment]
> Should we name the classes with capital letters? i.e. ufunc_ops.abs vs ufunc_ops.Abs. The second follows the naming style by being a class, while the first one follows numpy and may thus be easier for users. I say we go for capital first letter.

Totally for capitalized first letter.



> Let users access them in the top layer (odl.Abs). I vote against this due to clutter and possible collisions.

Clutter is a major issue for this approach. Clashes could be avoided with naming them `<xyz>UfuncOperator`, but that makes them sound "magical" and users won't touch them.



> Make them properties of the space, similar to vectors. I.e. space.ufunc.abs(x) == x.ufunc.abs(). I'm against this as well since we have so far not made operators that tightly coupled with the space, and I think this may make extension hard. But it is certainly an option.

In some way the problem here is similar to he top-level approach. It adds a ton of attributes to a class, which is clearly a sign that a functional approach is to be preferred here. Apart from that, they would also be hard to sort together for auto-completion in a sensible way without obfuscating the names.



> Create a new package like odl.ufunc_ops, odl.ufuncs or w/e. Users call e.g. odl.ufuncs.Abs(space)(x). I think this is the most clean solution.

Yes I agree. I'd prefer `ufunc_ops` since it signalizes that it contains operators. Having a telling name is a bit more important here since we're not going to import to top level.

> How will we handle things like derivatives? I'm guessing all of these will boil down to a MultiplyOperator, but how to chose it and how do we specify what is the derivative of what? e.g. odl.ufuncs.sin(space).derivative(p)(x) == odl.ufuncs.cos(space)(p) * x, but unless we manually write the ~30 or so ufunc classes adding all of these in a nice manner will be hard.

Hard to see a way that doesn't involve manual addition. We could make things a bit easier for ourselves by adding the most important ufuncs first and further ones on demand or when bored.



> How do we handle things with several input/output? e.g. add(x, y)? Do we make the domain a productspace? e.g. odl.ufuncs.add(space)([x, y]) == x + y.

Not sure if this is so useful anyway. Are there more interesting ones? But anyway, since we have no operators in several variables, using a product space is the only sensible way to do it. Important for the definition of derivative (and adjoint), too.

**Comment by adler-j** [comment]
Totally wild suggestion that just popped my mind. When `__numpy_ufunc__` is in, we could technically allow

```
>>> space = odl.rn(3)
>>> AbsOp = np.abs(space)
>>> AbsOp([-1, 2, 3])
rn(3).element([1, 2, 3])
```

not sure if this is good or not, but it sure is interesting.

**Comment by aringh** [comment]
My basic reaction is that it looks very convenient :) But I think we should provide a more "rigorous"  way also, like `AbsOp = odl.UfuncAbsOp(space)`.

**Comment by kohr-h** [comment]
> When __numpy_ufunc__ is in,

Any update on that? Last time I looked, the situation seemed to have somewhat stagnated.



> we could technically allow
> 
> >>> space = odl.rn(3)
> >>> AbsOp = np.abs(space)
> >>> AbsOp([-1, 2, 3])
> rn(3).element([1, 2, 3])
> 
> not sure if this is good or not, but it sure is interesting.

The idea is intriguing, and since we anyway go for a functional approach, I don't see a reason not to consider it.

**Comment by adler-j** [comment]
> Any update on that? Last time I looked, the situation seemed to have somewhat stagnated.

Looks dull right now.
