### ISSUE TITLE
Possible to cast discretization elements to each other

### ISSUE THREAD

**Issue by aringh** [odlgroup/odl#568]
Currently it is possible to cast discretizations with the same number of points to each other:

``` python
>>> import odl
>>> space_1 = odl.uniform_discr(0,1,10)
>>> elem = odl.util.testutils.noise_element(space_1)
>>> elem
uniform_discr(0.0, 1.0, 10).element([-1.5788431362508735, 0.14589381806476573, -0.73630405108690089, ..., 0.11649279784964384, -1.5782085999891313, 0.0077002321540446282])
>>> space_2 = odl.uniform_discr(1,2,10)
>>> elem_2 = space_2.element(elem)
>>> elem_2
uniform_discr(1.0, 2.0, 10).element([-1.5788431362508735, 0.14589381806476573, -0.73630405108690089, ..., 0.11649279784964384, -1.5782085999891313, 0.0077002321540446282])
```

Is this the behavior we want?

**Comment by kohr-h** [comment]
I'm inclined to think that this behavior is actually okay. The `space.element()` method is the "entry point" for "dirty" things, so to say, and if we accept nested sequences, Numpy arrays etc. as input, we should also accept other space elements. To me, `element` is an explicit caster.

So my view on this is that whenever a piece of code **really** needs something to be in a particular space, it should check space membership. Otherwise, if compatible input is acceptable, `element` is the thing to do.

**Comment by adler-j** [comment]
I agree with @kohr-h here, any fix would be a bad fix so to say since it would break the universality of `space.element`.

**Comment by aringh** [comment]
I am in no way against this conclusion. I just wanted to make it explicit that this is what we want and expect.

**Comment by kohr-h** [comment]
> I am in no way against this conclusion. I just wanted to make it explicit that this is what we want and expect.

Good you brought it up!
