### ISSUE TITLE
Functionals for the Kulback leibler divergence

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#612]
This is needes as part of #569, namely the "denoising with entropy typ regularization". I am honestly not sure if I can solve this one myself with a reasonable effort. Perhaps @aringh can have a look?

**Comment by aringh** [comment]
I will do it :)

**Comment by aringh** [comment]
I have created a branch and made a first implementation. But it only contains the `kl` and not the `kl_cross_entropy` functional, and even the `kl` functional lack some things (gradient for convex conjugate).

And, more sever, I have not had time to create any tests!

But, since this is wanted/needed for #569, I did what I have time for now. Unfortunately I will probably not have much time until end of next week at earliest. So either @adler-j takes it from here, or I will continue as soon as I have time :)
