### ISSUE TITLE
Rename NumpyNtuples to NtuplesNumpy etc

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#700]
We currently have a weird naming convention:

* `NumpyNtuples` <-> `NtuplesBase`
* `NumpyFn` <-> `FnBase`

In all other classes we always put the `Base` at the end, which I find more pleasing, and for symmetry the `Numpy` should come at the end as well. Hence I propose:

* `NumpyFn` -> `FnNumpy`
* `NumpyFnVector` -> `FnVectorNumpy`
* `NumpyNtuples` -> `NtuplesNumpy`
* `NumpyNtuplesVector` -> `NtuplesVectorNumpy`

This should make little difference for users since they seldom use these directly anyway.

**Comment by kohr-h** [comment]
Some of them make sense IMO, some don't really. I go along with `FnNumpy`, although I find it inferior from a "read and understand" perspective. On the other hand, `FnVectorNumpy` is a no-go, just ugly.

Can't we instead change the base guys to `BaseFn` and `BaseNtuples`? Grouping-wise I think it makes sense to keep all `Numpy` classes together, then all `Cuda` and so on.

**Comment by adler-j** [comment]
Well we have lots of other bases `FourierTransformBase` etc, I feel that having them all named the same way would be nice, and I find

* `BaseFourierTransform`
* `InverseFourierTransform`
* `FourierTransform`

much worse than

* `FourierTransformBase`
* `FourierTransformInverse`
* `FourierTransform`

This was my main motivation for suggesting this.

Regarding ugly, I dont think it matters that much since these are all "internal" classes, the most important is that we are consistent.

**Comment by kohr-h** [comment]
I know of all these, and there it's clearly better to group them by "implemented feature" rather than implementation. But for the `Ntuples` and `Fn` classes, I don't see that clearly that grouping by feature is the obvious thing to do, rather than grouping by implementation.

Consistency is good, but it's easy to overdo it. Being super-consistent and super-explicit, for example, results in class names like the ones in STIR. Not that it's obviously wrong, but I feel it doesn't help after a certain point.

Anyway, so a suggestion that I would agree on would be `FnNumpyVector` instead of `FnVectorNumpy`, which is consistent with our "element type = space type + 'Vector' / 'Element'" policy, while composing the space name in the consistent way you proposed further up.

**Comment by adler-j** [comment]
Agree that `FnNumpyVector` is a valid suggestion as well, I'll try to get this fixed.

This became obvious to me when writing the article and I noticed we were not being consistent.

**Comment by adler-j** [comment]
Agree that `FnNumpyVector` is a valid suggestion as well, I'll try to get this fixed.

This became obvious to me when writing the article and I noticed we were not being consistent.

**Comment by adler-j** [comment]
Agree that `FnNumpyVector` is a valid suggestion as well, I'll try to get this fixed.

This became obvious to me when writing the article and I noticed we were not being consistent.

**Comment by adler-j** [comment]
This whole issue is old given that we're moving to tensor naming, closing.
