### ISSUE TITLE
Change use of refs.rst

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#713]
Current we have a file, [refs.rst](https://github.com/odlgroup/odl/blob/master/doc/source/refs.rst) where we put most of our references. For the "pure" documentation this makes perfect sense, since any user would be viewing them at the [documentation page](https://odlgroup.github.io/odl/) where the links work perfectly. See for example [the reference to SW1971 in the fourier transform doc](https://odlgroup.github.io/odl/math/trafos/fourier_transform.html).

On the other hand, in the inline documentation this makes the reference basically un-usable. How is a user supposed to decipher the line [`For reference on the forward-backward primal-dual algorithm, see [BC2015]_.`](https://github.com/odlgroup/odl/blob/b387ddb7d2eb104d4d801ac411082cde991a79fd/odl/solvers/nonsmooth/forward_backward.py#L142)? The only way I can think of is by opening a web browser and looking up the [documentation there](https://odlgroup.github.io/odl/generated/odl.solvers.nonsmooth.forward_backward.forward_backward_pd.html?highlight=forward_backward_pd#odl.solvers.nonsmooth.forward_backward.forward_backward_pd), where the link actually works.

My proposal is to make all inline references fully written out in place, or in a references list (at the end of the docstring). Any reference in the non-inline doc should stay as is, or be moved to the bottom of the file where it is referenced.

**Comment by kohr-h** [comment]
Good suggestion, just a comment for clarification.

The main problem at hand is that the `References` section in a docstring is not explicitly printed if it only contains, yes, references. That is, stuff that begins with `..`, including citations `.. [label]`, hyperlinks `.. _Link text` and further stuff. This behavior makes perfect sense because the main reason for a reference is to be substituted for a label which becomes clickable and refers to the item behind the reference.

Citations are a special case of references because they are [global, i.e. accessible in all of the documentation](http://www.sphinx-doc.org/en/stable/rest.html#citations). I don't know what will happen when there are duplicate labels (which there are already, see for example the quasi-Newton methods) or even conflicting labels. At the least, we'll get heaps of warnings.

I'm not sure if this is the same suggestion as yours, @adler-j, but mine is to just add to the `References` sections the explicitly written out citations without making them a reference, and keeping the central `refs.rst` file to avoid label conflicts.

**Comment by adler-j** [comment]
I'm not quite sure what your suggestion is @kohr-h, could you format this docstring according to your proposal:

```
"""Douglas-Rachford primal-dual splitting algorithm.

References
----------
For references on the algorithm, see algorithm 3.1 in [BH2013]_.
"""
```

**Comment by kohr-h** [comment]
Ah, an exercise :-)
Okay here it is:

```
"""Douglas-Rachford primal-dual splitting algorithm.

For a description of the algorithm, see algorithm 3.1 in [BH2013]_.

References
----------
[BH2013] Bot, R I, and Hendrich, C. *A Douglas-Rachford type
primal-dual method for solving inclusions with mixtures of
composite and parallel-sum type monotone operators*. SIAM Journal
on Optimization, 23.4 (2013), pp 2541--2565.
"""
```
The `refs.rst` file stays as it is, to avoid duplication and conflicts.

**Comment by adler-j** [comment]
Fine with this proposal

**Comment by adler-j** [comment]
I'll self assign this and get it done.
