### ISSUE TITLE
Release 0.5.3

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#757]
Since the last release we have added lots of functionality, so we should actually make a new release to let users access all of this.

My proposal is that before 0.5.3 we do the following:

* Finish review of #756.
* Finish implementation of FFT/Wavelet fixes (#733)

We then dedicate 0.6.0 to the tensors or convolution, whichever comes first.

**Comment by adler-j** [comment]
Bump on this, we have added LOTS since the last release.

**Comment by kohr-h** [comment]
Of course. Agreed, the first PR is merged, the second not far, so it's totally time to wrap it up (perhaps we should do that more often).
My guess is that tensors will be first, since I'm putting more energy into it - seems more important. The PRs are not that far from completion, although tests still fail and all that, but things look rather good already.

**Comment by kohr-h** [comment]
How about we make a release now and keep #733 for 0.5.4? I think it's time for a release and I cannot say how much work #733 still is.

**Comment by adler-j** [comment]
Well I can live with that, especially since we have a partial fix of #733. But we REALLY need to get it fixed.
