### ISSUE TITLE
Making solvers class instances

### ISSUE THREAD

**Issue by aringh** [odlgroup/odl#76]
Right now solvers, like [the Newton solver](https://github.com/odlgroup/odl/blob/master/odl/solvers/vector/newton.py) are functions. It has been discussed before that they should maybe be classes instead. The reason for this, in particular in the case of the Newton solver, is that one may want to use this solver, but would like to provide another "sub-solver" than for example cg for solving the search direction (see also the [TODO comment](https://github.com/odlgroup/odl/blob/master/odl/solvers/vector/newton.py#L107-L110)). (I'm currently in this situation, therefore this new issue).

In order to do so we, among other things, need to standardize what interface these "sub-solvers" should have. After talking some to @adler-j, I suggest that given input to these solves should be the operator, the rhs and a initial guess. The interface for the Newton solver would then be something like
```python
class newtons_method(object):
    __init__(op, line_search, num_iter=10, equation_solver=None, partial=None):
```
where `equation_solver` is a solver called later as `self.equation_solver(self.op, x0, rhs)`.

So:
* Is it a good idea to turn them into classes instead of functions?
* If so, which solvers should be turned from functions into classes? All of them?
* Is this a reasonable interface for all solvers? Or should only the most basic ones (like cg, ncg, ...) have it? Then what if I want to use a Newton solver as a "sub-solver" somewhere else?

**Comment by kohr-h** [comment]
This issue has some overlap with #50, #51 and #52. Good to reactivate the discussion.

> Is it a good idea to turn them into classes instead of functions?

In general, I think that one should always try to use functions instead of classes if possible. As long as the amount of input (initialization) data is somewhat limited and there is not much internal bookkeeping and auxiliary calculation going on, I don't think one really needs a class. So it really depends. I suggest that we first agree on an interface for the `equation_solver` and decide later if we really need a class.

> Is this a reasonable interface for all solvers? Or should only the most basic ones (like cg, ncg, ...) have it? Then what if I want to use a Newton solver as a "sub-solver" somewhere else?

Hard to say. It seems to be closely related to the problem of categorizing methods. Here again a list of aspects to differentiate, maybe that gives some hints:

1. solver for `A(x) = 0`
2. solver for `A(x) = b`
3. solver for `Ax = b`, `A` linear (plus additional conditions like `A=A^H > 0`), 
4. minimizer of `A` over all of `R^n`
5. minimizer of `A` over some set
6. solver requires the continuous `A` to be defined on `R^n` vs. an infinite-dim. space
7. Requires advanced concepts like duals etc. (basic <-> advanced)

**Comment by adler-j** [comment]
Interesting write-up and I think we may need something like this in the long run. One reason to allow solvers to be classes is that they can then carry state (for example, pre-allocate memory in the case of a inner solver). I do certainly see the point for not using classes to much, it could cause quite some issues and makes the syntax ugly. I.e.

```python
solver = NewtonSolver(num_iter=10, solver=something)
NewtonSolver(A, x, b)
```

vs

```python
newtons_method(A, x, b, num_iter=10, solver=something)
```

Finally, one way to solve the problem mentioned by @aringh is to require that `equation_solver` is `callable`, then we could use either a class with `__call__`, a free function, or if we want to modify it, we define a lambda:

```python
# definition
def newtons_method(op, line_search, num_iter=10, equation_solver=None, partial=None):
    ...
    equation_solver(op, b, x)
    ...

# call
equation_solver =  lambda A, b, x: conjugate_gradient(A, b, x, num_iter=3)
newtons_method(..., equation_solver, ...)
```

**Comment by adler-j** [comment]
Do we have a resolution to this? Is my suggestion sufficient?

**Comment by aringh** [comment]
To me the last alternative, to force things to be `callable`, seems like a good option. Maybe one could think of doing something similar for the same for step-length classes #50 ?

**Comment by adler-j** [comment]
I say yes. Tbh I think we should do the same with the `Partial` thing, this would make some simple cases more easy to do.

**Comment by kohr-h** [comment]
I (finally) see three points speaking in favor of classes:

1. Possible optimization by allocating temporaries which can be used during the iteration.
2. Unification of the signature (although there is no way to really enforce it)
3. (and most importantly) Classes may be flexible and complex in initialization while functions should be easy to call.

So in my view, we probably are best off with an approach similar to the discretization. When using all the low-level class initializers, it's quite hard to get the final `DiscreteLp` structure, but with `uniform_discr`, which covers probably 95 % of the use cases, it's very easy.

In the solvers context, this would mean that the actual solvers are classes with (possibly) quite a number of parameters and high flexibility, while we have factory (or helper) functions which make the most common use case easy.

**Comment by adler-j** [comment]
Valid point holger, basically you are suggesting:

```python

def LandweberSolver(...):
    def __init__(tmp_dom, tmp_ran, niter, omega, partial=None):
        self.tmp_dom = tmp_dom
        self.tmp_ran = tmp_ran
        self.niter = niter
        self.omega = omega
        self.partial = partial

    def __call__(op, x, rhs):
        for _ in range(niter):
            op(x, out=self.tmp_ran)
            self.tmp_ran -= rhs
            op.derivative(x).adjoint(self.tmp_ran, out=self.tmp_dom)
            x.lincomb(1, x, -self.omega, self.tmp_dom)

            if self.partial is not None:
                self.partial.send(x)
        return x
                
                
def landweber(op, x, rhs, niter=1, omega=1, partial=None):
    tmp_dom = op.domain.element()
    tmp_ran = op.range.element()
    solver = LandweberSolver(tmp_dom, tmp_ran, niter, omega, partial)
    return solver(op, x, rhs)
```

**Comment by kohr-h** [comment]
Yes, either this (a caller helper or whatever you would call such a function) or a factory for the class. A matter of taste, I guess. This is the easier pattern, just call the method, end of story. An advantage with the factory would be that one could inspect the state after a specified number of iterations. This would make it possible to run, say 20 iterations, check (or plot) something, then warm-start the method for another 50 iterations etc.

**Comment by kohr-h** [comment]
Or make a new method and warm-start with the result of the previous one.

**Comment by kohr-h** [comment]
For that last thing, which I think would be a great functionality, a unified state structure would be extremely helpful for communication between solvers. Then one could implement
```python
class Landweber(...):
    @classmethod
    def fromstate(state):
        # Check if there is enough information for a warm start in state
        instance = Landweber(...)
        instance._cur_state = state
        return instance
```

**Comment by adler-j** [comment]
> Yes, either this (a caller helper or whatever you would call such a function) or a factory for the class. A matter of taste, I guess. This is the easier pattern, just call the method, end of story. An advantage with the factory would be that one could inspect the state after a specified number of iterations. This would make it possible to run, say 20 iterations, check (or plot) something, then warm-start the method for another 50 iterations etc.

If the user wants a persistent object, what's wrong with (possibly with somewhat improved syntax)

```python
solver = LandweberSolver(..., niter=20)
solver(op, x, rhs)

plot(x)

solver.niter = 50  # maybe make this some method
solver(op, x, rhs)

...
```

> For that last thing, which I think would be a great functionality, a unified state structure would be extremely helpful for communication between solvers. Then one could implement ...
    
Im quite sceptical to this, mostly because enforcing this would cause quite a hassle programming wise. Whats wrong with simply having persistent instances of the solvers?

**Comment by kohr-h** [comment]
> If the user wants a persistent object, what's wrong with (possibly with somewhat improved syntax)

Sure, as long as the class constructor is easy enough. I was trying to say that factories can be useful if class constructors are complicated to use due to "low-levelness", and that on the other hand, low-level class constructors with many parameters can also be useful if we want a certain amount of flexibility. We should not be forced to keep the class constructor simple if there is a good reason not to. Of course, there is not need to overcomplicate things right now, but things may change over time.

> Im quite sceptical to this, mostly because enforcing this would cause quite a hassle programming wise. Whats wrong with simply having persistent instances of the solvers?

Well, some things you can, of course, do already now, e.g. do 50 Landweber iterations and use the result as starting value of some other scheme (I'm not saying this has to make sense). But if scheme 1 happens to e.g. use gradients in its iteration and scheme 2 does, too, then the last one could use the last gradient (or last 2 gradients?) for its warm start.

This state thing doesn't have to be super-complicated, but we need to do something if we want to have a unified call pattern for step length calculators. Not all of them use the function and its gradient, some may use the residual or past step lenghts etc.

**Comment by adler-j** [comment]
What do we do about this? I say we keep the current way since changing it would complicate lots of things. Adding optional tmp_ran and tmp_dom where needed could likely solve most of the issues mentioned here, no?

**Comment by kohr-h** [comment]
I agree. Currently I don't know what big benefits we would have by stateful reconstruction methods. We are anyway more interested in the advanced stuff with proximals and all that. And there, in my view, the situation is such that

- the methods are completely abstract anyway in the sense that they are as generic as possible and make use of external functionality for maximal flexibility, and
- they are different enough in input, output, iteration, number of parameters, etc. such that it would not make much sense to try finding a unified scheme.

The plugin-like architecture we attempted in the step length classes failed in my view, since we never managed to unify their syntax and usage pattern in a way that includes all present examples (about 3). Implementing the necessary book-keeping framework for the quantities needed for a step size calculation (which iterates, gradients, ...) would be a considerable hassle. I think we should have a very good reason for trying to do the same for solvers in general. Currently I don't see one.
