### ISSUE TITLE
Add an ODL DOI to make the repository cite-able

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#764]
We can make the repository in itself citeable using [these steps](https://guides.github.com/activities/citable-code/).

Do we want to do this, or are we waiting for the article instead? See #397.

**Comment by kohr-h** [comment]
I think that's a very good idea. Better something suboptimal than nothing at all. And we can ourselves cite it in the article^^

**Comment by kohr-h** [comment]
Ping @ozanoktem

**Comment by kohr-h** [comment]
Ping again

**Comment by ozanoktem** [comment]
Well, I tried to follow the [instructions](https://guides.github.com/activities/citable-code/) to assign a DOI to the ODL repository but it did not work out. After login into Zenodo using my GitHub account, there are no GitHub repositories that I can select since I'm told I have no such repositories.

**Comment by kohr-h** [comment]
You forgot to grant access on the organization level when the screen came up (the "odlgroup" switch had to be checked). I did this now. The DOI will be created with the next release.
