### ISSUE TITLE
Documentation not built for release 0.5.3

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#827]
The documentation is still at 0.5.2:

https://odlgroup.github.io/odl/index.html

Is the build working properly?

**Comment by kohr-h** [comment]
Hard to say. 
- At the [Travis page for branches](https://travis-ci.org/odlgroup/odl/branches) the last built commit is 7cd07fc26772c2d30c8ebd5eb92770c86e8b7dc8, 2 days ago.
- In the [build history](https://travis-ci.org/odlgroup/odl/builds) the last item is e68bee1, also 2 days ago. 
- In contrast, the [current build](https://travis-ci.org/odlgroup/odl) is 9c43393, which is from #828.

Confusing. But in any case, there's no build for master after the merge of #821.

**Comment by adler-j** [comment]
It seems this may have been my fault, maybe.

As mentioned in private correspondence with you, I removed one of the travis builds, it seems this may have been the one you had set the doc to build on?

**Comment by kohr-h** [comment]
> As mentioned in private correspondence with you, I removed one of the travis builds, it seems this may have been the one you had set the doc to build on?

Don't quite recall that. 
In any case, currently the doc is not built for pull requests, mainly because otherwise you have to wait for ages every time you push something to a branch that is supposed to be pulled in.
But when the branch is merged and `master` is updated, Travis is supposed to make a build again, then also building the docs. If that build is canceled or not triggered, the docs are not updated, of course.

I saw that "build pushes" was switched off in Travis, that may be the reason. Switched it on again, let's see what happens.
I also added a cron build that builds master daily if there hasn't been a build in the past 24 hours already.

**Comment by kohr-h** [comment]
Successfully built now.
I switched the "build pushes" off again, I don't think we need the updated doc right away after an update on master, once per day should be enough.

**Comment by adler-j** [comment]
Great!
