### ISSUE TITLE
len or/and size or/and shape for BroadcastOperators

### ISSUE THREAD

**Issue by MatthiasJE** [odlgroup/odl#899]
I am creating a broadcast operator as follows 

```python
listOps = list()
for i in range(n):
    listOps.append(I)
    
A = odl.BroadcastOperator(*listOps)
```

which is nothing else than a stacked operator with `n` blocks. The question is now, how to retrieve `n` from `A`? One solution that works is: `len(A.range)` but this is not really intuitive as it requires the existence of the `A.range` attribute. It would be more elegant if a `BroadcastOperator` (and in fact any product operator) supports things like `len(A)`, `A.shape`, `A.size`.

**Comment by adler-j** [comment]
I think len(A) should work, other than that the suggestions are great and I'll get them in!

**Comment by MatthiasJE** [comment]
Here is some code I tried:
```
A
Out[8]: BroadcastOperator: uniform_discr([0.0, 0.0], [1.0, 1.0], (128, 128)) -> ProductSpace(uniform_discr([0.0, 0.0], [1.0, 1.0], (128, 128)), 100)

len(A)
```
Traceback (most recent call last):

  File "<ipython-input-9-97773d940b55>", line 1, in <module>
    len(A)

TypeError: object of type 'BroadcastOperator' has no len()

**Comment by adler-j** [comment]
There is a pull request adressing most of this in the pipeline right now. Some corner cases need to be solved before we finally go ahead, but it should be simple.

@kohr-h: The corner case is what `ReductionOperator.shape` and `BroadcastOperator.shape` should be. I need input here. The problem is that `ReductionOperator` is "kinda" a row vector, and hence should have `shape == (n,1)`, or perhaps `shape == (n,)`. On the other hand `BroadcastOperator` is "kinda" a column vector, but should then have `shape == (1, n)` or `shape = (n,)`.

If we let the shapes both be `(n,)`, we're kinda fine, but we lose the row/column interpretation. Meanwhile if we go for `(n, 1)`/`(1, n)` the column/row interpretation stands, but then we would expect indexing to be two dimensional, which we don't want.

One option is to simply not add `shape` to them since it will be confusing either way. Users can still use `len` and `size`.

**Comment by kohr-h** [comment]
I see. Both possibilities have their advantages. Row/column interpretation is closer to Numpy style indexing, and people who actually know what these operators do would perhaps expect that they act like operator rows/columns.

On the other hand, we went so far as to create two new operators for these special cases, so there is some freedom of choice here.

More general question: why did we create the two new classes in the first place? Was it to be able to operate on a single space element as input / produce a single space element as output?

Perhaps we should take a step back and consider if it wouldn't be simpler to let `ProductSpaceOperator` handle all those cases. That would basically require that they have to accept a base space element (instead of a 1-sequence) as input if there's only one column, and perhaps to produce a base space element as output if there's only one row. The `__call__` could wrap input into a tuple before calling the parent `__call__` to avoid further hassle.

But anyway, withing the suggestions I would prefer defensive tactic of not adding shape for now.

**Comment by aringh** [comment]
I think that they are both nice features, since the row and column cases are a bit more special than a general matrix case.

For example, if I have a row-vector of operators it is very convenient if the range is the range of the operators, not a `ProductSpace(my_space, 1)`, which `ProductSpaceOperator` will create. Hence I think that their existence is well-motivate.

Regarding `shape` I have not good input: you know better than me.

**Comment by adler-j** [comment]
Certainly agree with @aringh that they have a reason for existing and they were created specifically to solve the issue that @aringh is mentioning: avoiding domains and ranges that are simply `ProductSpace(my_space, 1)`.

The other option, that `ProductSpaceOperator` should solve this automatically would break the ODL style in several ways, and would still be ambiguous w.r.t. the return value in the case of `ReductionOperator` (should it be `ProductSpace(my_space, 1)` or `my_space`? Perhaps different application want different options)

Perhaps we can settle on leaving shape un-defined for now?

**Comment by adler-j** [comment]
Then this issue can be closed.

Thank you for the input @MatthiasJE! Small improvements like this truly help our users :)
