### ISSUE TITLE
proximal operators with matix valued "step size"

### ISSUE THREAD

**Issue by mehrhardt** [odlgroup/odl#904]
ODL currently assumes that the "step size" (usually called sigma) of a proximal operator is a scalar. However, in some applications (including mine) the step size may be a matrix. In my case it is a diagonal matrix. See for instance:

Pock, T., & Chambolle, A. (2011). Diagonal preconditioning for first order primal-dual algorithms in convex optimization. Proceedings of the IEEE International Conference on Computer Vision, 1762–1769. http://doi.org/10.1109/ICCV.2011.6126441

Plugging in matrices causes errors like

```
Traceback (most recent call last):

  File "<ipython-input-12-e4a6eb3427f7>", line 58, in <module>
    outputFun=outfunLocal,verbose=verbose)

  File "/home/ehrhardt/repositories/git_matthias_ehrhardt_CIA/python/src/optimization/PDHG_odl_.py", line 95, in PDHG_block_odl
    x, y, Kadjy, AdjYbar = PDHG_iteration(x, y, AdjY, AdjYbar, F, G, Op, sigma, tau, prob, theta, selected )

  File "/home/ehrhardt/repositories/git_matthias_ehrhardt_CIA/python/src/optimization/PDHG_odl_.py", line 119, in PDHG_iteration
    x = G.proximal(tau)(x - tau * AdjYbar)

  File "/home/ehrhardt/repositories/git_ODL/odl/solvers/functional/functional.py", line 456, in proximal_left_scalar_mult
    return self.functional.proximal(sigma * self.scalar)

  File "/home/ehrhardt/repositories/git_ODL/odl/solvers/nonsmooth/proximal_operators.py", line 146, in cconj_prox_factory
    sigma = float(sigma)

  File "/home/ehrhardt/repositories/git_ODL/odl/space/base_ntuples.py", line 387, in __float__
    raise TypeError('only size 1 vectors can be converted to float')

TypeError: only size 1 vectors can be converted to float
```

**Comment by adler-j** [comment]
Ironically, I tried exactly what you say in this issue: #379 but made marginal progress.

This is a long term problem however so we should really get it done.

Obviously the alternative to "matrix valued" would be operator valued in ODL, I'll see if i can find where this causes problems.

**Comment by MatthiasJE** [comment]
Sorry for me not finding #379. I haven't even thought of that this issue was there before as this is more of a niche topic. I am happy to help here if you need any input though I am not sure I can really help yet on the coding front as I am not too much into the style of ODL.

I have implemented this for my own code in python and most of the things are quite straight forward. Probably the most troubling thing is that there are not many "rules" you can apply for operator valued step sizes like Moreau's identity. I suppose every prox operator with operator valued step sizes has to be hard coded for every case.

**Comment by adler-j** [comment]
> Sorry for me not finding #379. I haven't even thought of that this issue was there before as this is more of a niche topic. 

No problem, there is quite a few of them by now and that was only a special case (where this was needed).

> I am happy to help here if you need any input though I am not sure I can really help yet on the coding front as I am not too much into the style of ODL.

> I have implemented this for my own code in python and most of the things are quite straight forward. Probably the most troubling thing is that there are not many "rules" you can apply for operator valued step sizes like Moreau's identity. I suppose every prox operator with operator valued step sizes has to be hard coded for every case.

Well, if you want you could always make a pull request where you modify the specific parts you want modified and we could help you out with final touches and ODL style questions. Another option is that you provide your code and I can have a look at how we can integrate it. Any input is warmly welcomed!

Worst case I'll have a look at this but it is nontrivial and we're currently focusing on getting the monster pull-request #861 in, so it will have to be after that.

Even so we would need to do a theory push. Do you have any sources on this that could be used as a reference?

**Comment by MatthiasJE** [comment]
The only source I know so far is the one I cited at the top and probably soon another one of mine ;) I will have a look to solve this myself in the next days/weeks and let you know about my progress.

**Comment by adler-j** [comment]
Ok, too bad (except for you :D). I'd love to hear about any progress and help out in adding this. Even a subset, e.g. supporting it for the two-norm squared would help in many cases.

**Comment by MatthiasJE** [comment]
Thinking about this again, it would be probably a good first step to only allow this for sums of N separable functionals and only if the "step size" is a vector of length N so that the prox operator is just the normal prox operator but the scalar step size varies with the component. Is this easily doable?

In general one might want to exploit the identity
```
$$ prox_R^S(f) = S^{1/2} prox_{R \circ S^{1/2}}^I (S^{-1/2} f)$$
```
with 
```
$$prox_R^S(f) = \argmin_x \frac12 \| S^{-1/2}(x - f) \|^2 + R(x).$$
```
However, in general it is not clear how to compute 
```$$prox_{R \circ S^{1/2}}^I (S^{-1/2} f)$$```

**Comment by adler-j** [comment]
Well what you say can be rather easily implemented as long as you only need it in `SeparableSum`. There we could add a parameter like `proximal_weighting`, or similar and then simply scale the scalar step length by this vector.

Doing so wouldn't cause much of an issue.

The general case, as you note, is not as simple.

**Comment by sbanert** [comment]
I thought about this issue again, and besides integrating list-valued stepsizes for SeparableSum functionals, one would also have to integrate the most important decooposable basic functionals, like the ℓ¹/L¹ norm (and their conjugate) and the squared ℓ²/L² norm. Since this seems to require some nontrivial adaptions in several functions, I want to discuss this before spending time on it:

My idea is that instead of having a single number as “stepsize”, one would take an element of the space instead, and the classical approach would correspond to a multiple of the vector `space.one`.
The Moreau decomposition formula would then be evaluated with element-wise division and multiplication.

For the ℓ¹ norm, the procedure is as follows: Its conjugate is the indictator function of the ℓ^∞ unit ball, thus its proximal is independent of the step size. For the ℓ¹ norm itself one would use Moreau’s formula (this is the also the way it is implemented now). For the ℓ² norm this is done essentially the same way, and this could possibly even applied for function spaces with pointwise instead of elementwise operations. The operations of functionals like shifting and scaling must also be tested (and possibly adapted) for these “stepsizes”.

The easiest way would be to implement these separable standard functionals as `SeparableSum`’s, but I’m afraid that this would produce a significant computational overhead.

**Comment by adler-j** [comment]
Very nice run-through @sbanert. I certainly agree that the approach you suggest sounds nice, and further your final comment regarding simply doing everything with `SeparableSum` is certainly correct, that would not be acceptable.

My suggestion would be that you try doing something absolutely minimal (e.g. make this work with only the l2-norm) and see how the interface looks. If it's good, then go ahead.

**Comment by sbanert** [comment]
Should we close this now that #1166 is merged? I am afraid that general “matrix valued” stepsize will never be possible because there do not exists formulas except for some special cases.

**Comment by adler-j** [comment]
Ok, lets close this then!
