### ISSUE TITLE
plotting into subplots, .show() into subplots

### ISSUE THREAD

**Issue by MatthiasJE** [odlgroup/odl#905]
I tried to plot images with ODL into subplots with the following code which did not work. By now I figured that it is not supposed to work but this would be a desirably functionality indeed.

```python
import odl
import matplotlib.pyplot as plt

X = odl.uniform_discr([0,0], [1,1], [128,128], weighting="none")
x = odl.phantom.shepp_logan(X, modified=True) # I guess people expect the modified version as the default

fig = plt.figure(1)
fig.add_subplot(1,2,1)
x.show(title="1", fig=fig);
fig.add_subplot(1,2,2)
x.show(title="2", fig=fig);
```

It is also not so clear what the default settings for x.show() should be. Plotting into a new figure or into the current one? I think for playing around plotting into a new one is better but for sophisticated work you (or at least I) would not want that.

**Comment by adler-j** [comment]
In general the `show` functions are not supposed to be used for more extensive plotting, more for quick prototyping, hence we haven't (and probably won't) be supporting specialized functionality like this. Mostly because it would give us a maintenance nightmare.

To get "ODL like" plots, you could simply use the respective functions yourself:

```python
import odl
import matplotlib.pyplot as plt

X = odl.uniform_discr([0, 0], [1, 5], [128, 128], weighting="none")
x = odl.phantom.shepp_logan(X, modified=True)

extent = [X.min_pt[0], X.max_pt[0], X.min_pt[1], X.max_pt[1]]

fig = plt.figure(1)
fig.add_subplot(1, 2, 1)
plt.imshow(x, cmap='bone', extent=extent, aspect='auto')
plt.xlabel('x')
plt.ylabel('y')

fig.add_subplot(1, 2, 2)
plt.imshow(x, cmap='bone', extent=extent, aspect='auto')
plt.xlabel('x')
plt.ylabel('y')
```

The parameter `fig` is actually mostly not suggested for regular use, but is mostly there in order to enable the `CallbackShow` functionality, where it lets us do stuff like real-time plotting (as you see in all examples).

The reason we create a new plot is that we want the most simple syntax to correspond to the most simple use case, i.e. the most simple use case is simply calling "`x.show()`" to see what's up. If we updated the current plot users would need to somehow specify that (e.g. `x.show(fig='new')`).

If updating the current figure is a usecase you are looking for we could add some option that basically uses the current figure without creating a new or using a specified one. We also need to agree on how you cant the colorbar to be handled. Would you still want a colorbar added, or do you want to do that yourself?

**Comment by MatthiasJE** [comment]
I do understand your reasoning regarding the subplots and the new figure. Maybe it is just good the way it is.

**Comment by adler-j** [comment]
Ok, closing this then.

I tried making a quickfix that would allow what you did, but the code is currently rather "self contained" and optimized to quickly give the user something usable, so adding it seems to make other things more complicated.
