### ISSUE TITLE
Default value for Operator.range

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#928]
Currently we require both a domain and range of an operator, but frankly there is an obvious value for the range: the domain. Hence i would suggest we make the `range` parameter optional.

Pros:
Makes scripts faster to write

Cons:
Non-obvious to some users?

**Comment by ozanoktem** [comment]
I don't like this suggestion. It is by no means natural and I also think it is good to force som degree of verbocity in code. Makes it much easier to read if one does not have to keep a number of non-natural deafult settings in mind.

**Comment by kohr-h** [comment]
We are currently very explicit when defining operators. For example, we usually explicitly write `linear=False` to make it very clear, despite the fact that it's the default.

I think there's a good reason to it, namely that operators are not always easy to understand conceptually in their entirety, especially when `domain` and `range` are different. So the more explicit we are, the more we help others to understand what we're doing. 

So IMO we should *always* write out `domain` and `range` in the operator initialization. And then we can as well keep them mandatory.

It may even have been a debatable choice to use a default for `linear`, but here at least the default `False` is a sensible one because "most" operators are not linear. That cannot really be said for the case of `domain` and `range`.

**Comment by adler-j** [comment]
Oh well, it was an idea :) But you make good points.
