### ISSUE TITLE
Automatic code quality checking

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#93]
I added [landscape](https://landscape.io/github/odlgroup/odl) a while back, but recently in #73 it started sending messages. This is somewhat obnoxious.

I'm considering adding something like this (perhaps [codacy](https://www.codacy.com/app/jonasadl/odl)) to the project. The issue might be that we add to many of these tools and keeping high quality of code will actually slow us down. Even now the process of doing a single pull takes abit too long in my opinion.

**Comment by kohr-h** [comment]
We have to be a bit careful, I agree. These tools are actually meant to help in finding bugs, comparing code quickly for review etc., so developers become more efficient. But in reality, it is easy to become obsessed with optimizing some figures (like the quite meaningless "code health"). Then one suddenly wastes time tracking down warnings and errors which only come from, e.g., Pylint not understanding our code properly (like the [operator](https://landscape.io/github/odlgroup/odl/111/modules/examples/simple_operator.py#L44) example).

Current times for pull requests are mostly due to us bouncing back and forth in iterations. I'm quite sure we're going to improve over time ;-).

**Comment by kohr-h** [comment]
Having said this, I think it is beneficial to have *something* to check the style so things don't easily slip through. This can be quite basic like a function or class not documented or some bad variable names. Here it can actually be quite helpful to quickly find such quirks.

**Comment by kohr-h** [comment]
Codacy and [Code climate](https://github.com/integrations/code-climate) seem to be a bit less annoying and better integrated into the PR machinery. And probably customizable to be even less annoying.

**Comment by adler-j** [comment]
I'll close this now with decision that we dont use any auto checking that spams us, but we can have the sites running. I suggest we also remove the .landscape.yaml file since it clutters the top level.

**Comment by kohr-h** [comment]
Yes, sure. When we later feel the need for such a thing, we can set up one.
