### ISSUE TITLE
scikit Radon adjoint has the wrong scaling

### ISSUE THREAD

**Issue by MatthiasJE** [odlgroup/odl#948]
I would like to discuss the scaling of the adjoint of the Radon transform similar to last summer. This time it is a bit different as it has to do with the weighting of the underlying space. Let us consider the following example.

```
X = odl.uniform_discr(min_pt=[-1, -1], max_pt=[1, 1], shape=[150, 150], weighting="none")
x = X.one()

angle_partition = odl.uniform_partition(0, np.pi, 150)
detector_partition = odl.uniform_partition(-2, 2, 250)
geometry = odl.tomo.Parallel2dGeometry(angle_partition, detector_partition)
op = odl.tomo.RayTransform(X, geometry)
```
Then we see that the adjoint test fails: 
`op.adjoint(op(x)).inner(x) / op(x).inner(op(x)) = 5699.3573114767005`
If we consider however the usually weighted space 
`X = odl.uniform_discr(min_pt=[-1, -1], max_pt=[1, 1], shape=[150, 150])`
then the adjoint test is "satisfied" as 
`op.adjoint(op(x)).inner(x) / op(x).inner(op(x)) = 1.0132190775958578`

Note that `1/X.cell_volume = 5625.000000000001` and `1.0132190775958578 * 5625.000000000001 = 5699.3573114767005`.

Next to this, I also noticed that the image of the Radon transform is always a weighted space (weighted by the cell volume). 
`odl.tomo.RayTransform(X, geometry).domain.one().norm() = 3.5449077018110318`
It might be a good idea to either be able to switch this off or to inherit this from the domain?

**Comment by adler-j** [comment]
This is a clear bug, and the fix is rather simple (as you say, simply disable the weighting in the adjoint). 

To do that, we would need to fix the following places:

https://github.com/odlgroup/odl/blob/ba175be5dc1437a2ce78f7be9744a2c227a648ff/odl/tomo/backends/scikit_radon.py#L146-L148

https://github.com/odlgroup/odl/blob/ba175be5dc1437a2ce78f7be9744a2c227a648ff/odl/tomo/backends/astra_cpu.py#L217-L222

https://github.com/odlgroup/odl/blob/ba175be5dc1437a2ce78f7be9744a2c227a648ff/odl/tomo/backends/astra_cuda.py#L284

Regarding the range, I feel that adding a parameter `range_weighting` would be nice, a default would be "same", e.g. use same style as domain, and then users could pick weighted, vs unweighted if they specifically want one.

Would you be interested in fixing this, or should I have a look? Currently very busy so it could take a while.

**Comment by MatthiasJE** [comment]
I think it might be better if you have a look. Thanks!

**Comment by adler-j** [comment]
Will do!

**Comment by MatthiasJE** [comment]
I have found another problem that is probably related, therefore I post it here and not under a new issue. I want to have "subsampled ray transforms" in ODL. By this I mean a Radon transform that only computes the output for a subset of the angles. Please find my attempt below. The problem is that the cell_size of the range is different. Why would that be?

import odl
import numpy as np

X = odl.uniform_discr(min_pt=[-75, -75], max_pt=[75, 75], shape=[150, 150])
angle_partition = odl.uniform_partition(0, np.pi, 150)
detector_partition = odl.uniform_partition(-150, 150, 250)
geometry = odl.tomo.Parallel2dGeometry(angle_partition, detector_partition)
ray_transform = odl.tomo.RayTransform(X, geometry)

geom_s = odl.tomo.Parallel2dGeometry(angle_partition[range(0,150,5)], detector_partition)
ray_transform_s = odl.tomo.RayTransform(X, geom_s)

ray_transform_s.range.cell_volume
Out[14]: 0.12566370614359174

ray_transform.range.cell_volume
Out[15]: 0.025132741228718346

**Comment by kohr-h** [comment]
That's expected since the range is just a "data cube", so the `cell_volume` includes the angular spacing. If you only want the detector cell volume, you can do `ray_trafo.geometry.det_partition.cell_volume`, which is the same as `np.prod(ray_trafo.range.cell_sides[1:])`, as long as we never switch the axis order :-).

**Comment by kohr-h** [comment]
Also, you can get every fifth angle by `angle_partition[::5]`.

**Comment by MatthiasJE** [comment]
Thanks @kohr-h for this explanation. Even if this behavior is anticipated, it still leads to problems. I want to have operators A_i that compute the Radon transform for subsets. In particular I want that \sum_i A^\ast_i x_i = A^\ast x where A^\ast is the backprojection of the whole Radon transform. How do I achieve this in ODL? The scaling is key here!

**Comment by kohr-h** [comment]
Do you want to split the angle interval or do you want to do interlaced splitting? The former is simple because the cell volume will not change, and the property you want will hold. The other is not "for free" because if you take every `n`-th angle, each one will be "responsible" for `n` times its original subinterval. To prevent that, you need to scale each operator again by `1 / n`.

The overarching issue is that it is the nature of partitions to cover whole intervals and there is no easy way to make "gaps".
Probably the most natural way to go about this would be to take on a fully discrete (at least in the angle variable) view of the ray transform and not do any scaling. In that case there wouldn't be an issue. I guess we should have an option for that in the `RayTransform` operator.

There's actually a stone age old issue related to this: #434. We also had some discussions in the context of SPECT about how to handle the case when you only have discrete values for your source positions.

**Comment by MatthiasJE** [comment]
> Do you want to split the angle interval or do you want to do interlaced splitting? 
Well, at the moment I want to do evenly interlaced splittings but in the future this might change. I think my problem is exactly the of #434 as I am working on extensions of ordered subsets algorithms :)

**Comment by kohr-h** [comment]
> Well, at the moment I want to do evenly interlaced splittings but in the future this might change.

Yes, so for efficiency reasons we should have an option in `RayTransform` that doesn't weight with angle spacing. Let me check how I would go about that, doesn't sound hard.



> I think my problem is exactly the of #434 as I am working on extensions of ordered subsets algorithms :)

Nice! I suppose you know that we have an OS-MLEM lying around that you could take as template for something similar?

**Comment by adler-j** [comment]
Nothing so far, but I'll get to it.

**Comment by adler-j** [comment]
I've made a pull request that should fix this. Just needs review etc now and then we can merge.

**Comment by adler-j** [comment]
This has finally been fixed. Terribly sorry for the long delay, I've been quite busy. Please let us know if there is any issues with the fix.

**Comment by MatthiasJE** [comment]
Thanks @adler-j for this! I am not sure whether this should be fixed, too, but the current code does not work for all geometries. Here is one example:


```
import odl
import numpy as np

a = 150
X = odl.uniform_discr([-a/2]*2, [a/2]*2, [a]*2)
n = 20
angle_partition = odl.uniform_partition(0, np.pi, a)[(n-1)::n],
detector_partition = odl.uniform_partition(-a, a, 250)
geometry = odl.tomo.Parallel2dGeometry(angle_partition,
                                       detector_partition)
op = odl.tomo.RayTransform(X, geometry)
x = X.one()
op.adjoint(op(x)).inner(x) / op(x).inner(op(x))
```
which gives `Out[48]: 1.1725176460741027` instead of 1. Any idea what is wrong here?

This is what I discussed with @kohr-h a few posts ago.

**Comment by adler-j** [comment]
What version of astra are you using btw?

**Comment by MatthiasJE** [comment]
This is scikit.

```
ray_transform.impl
Out[3]: u'scikit'
```

But I can confirm that scikit is not to blame. I have my own implementation based on scikit where this works well. However, it would be nice if I could do the same with proper ODL which allows easy handling of geometries, resolution etc.

**Comment by MatthiasJE** [comment]
Why is this issue now closed? I tried my previous example again and it still gives me the same results: 1.17... instead of 1.
