### ISSUE TITLE
"out" as non-optional argument?

### ISSUE THREAD

**Issue by MatthiasJE** [odlgroup/odl#962]
This is not really an issue, rather an implementation question.

In many ODL functions "out" is not declared an optional argument but still behaves as it was. Why is this? When I tried to write my own ODL prox operator this gave me a lot of headache as for me it did not behave like this. But rather than complaining it gave me nonsense as output.

Here is an example where I run a function without the "out" argument but the actual code does not declare it as being optional. Further, I define my own operator in a similar fashion but it does not behave similar

```python
import odl
from builtins import super

space = odl.uniform_discr([0, 0], [1, 1], [1, 1])
f = odl.solvers.proximal_cconj_l2_squared(space)
sigma = 2
x = odl.phantom.white_noise(space)

print(f(1)(x))

class Prox(odl.operator.Operator):

    def __init__(self, sigma):
        self.sigma = float(sigma)
        super().__init__(domain=space, range=space,
                         linear=False)

    def _call(self, x, out):
        out = 77
        return out
        
print(Prox(1)(x))
```
The output on screen:

```
[[-0.538313231696]]
[[-0.538313231696]]
```

**Comment by kohr-h** [comment]
This is expected since you bind the name `out` in `_call` to a new value, which is ignored by the wrapping `__call__`. Here's how it works:

- First of all, the reason why there is `_call` at all and you don't implement `__call__` directly is two-fold:
  1. `__call__` does all input and output checking for you and you can assume in `_call` that your input (and output) is exactly what you expect it to be.
  2. The interface to call `Operator` instances is *always* the same, no matter how `_call` is implemented. It always supports calling with and without `out` parameter.

- Then, ODL `Operator` distinguishes between 3 types of signatures of `_call`:
   1. `_call(x)`: out-of-place evaluation. In this case, `__call__` wraps the output in a `range.element()` if the calling code has no `out` otherwise it simply assigns `out[:] = result`.
   2. `_call(x, out)`: in-place evaluation. Here, `__call__` just passes through the `out` parameter if it has been given one, otherwise it creates a new one, `out = range.element()` and gives that to `_call()` (since `_call` needs one).
   3. `_call(x, out=None)`: dual use. In this case `__call__` will just pass through the `out` it got (after checking) since `_call` can handle both cases.

- Finally, the reason why your code `out = 77` has no effect is that you're in case 2 with an in-place implementation. In this case, `__call__` will *not* use the return value and assume that `_call` modifies `out` in place.

Probably the easiest way to understand this stuff is to go into [`Operator.__call__`](https://github.com/odlgroup/odl/blob/master/odl/operator/operator.py#L625-L705) and check exactly what the code does. There is also [a guide](https://odlgroup.github.io/odl/guide/operator_guide.html) on this topic, but maybe it lacks some details. Please give us feedback if you think the guide fails to make everything clear.

**Comment by kohr-h** [comment]
There is a related issue #935 where we discuss a different interface. You're welcome to comment.

**Comment by adler-j** [comment]
> In many ODL functions "out" is not declared an optional argument but still behaves as it was. Why is this? 

This is in order to provide a fixed interface so that users don't have to worry about if it was included or not.

> When I tried to write my own ODL prox operator this gave me a lot of headache as for me it did not behave like this. But rather than complaining it gave me nonsense as output.

This is actually a documented feature [see the doc](https://github.com/odlgroup/odl/blob/82d09d3d082d84ebd35766ada0847cb5695adadf/odl/operator/operator.py#L346-L410).

What is happening in your case is as follows (re-written from your example, but without overwriting the "out" name, for clarity).

Your function definition is equivalent to:

```python
def _call(self, x, out):
    out2 = 77
    return out2
```

Since this function has `out` as a required parameter, and you call it without the `out` parameter, the following happens in ODL:

```python
out = op.range.element()
op(x, out)
return out
```

Hence, the returned value from `op` is ignored, since your function definition indicates that you will use the out parameter. 

Since your function does not modify `out`, we make absolutely no guarantee about what the value of `out` will be, and it seems in your case it is re-using the memory adress of the last call, this is a pure coincidence.

A fix for you, if you want the returned value to be used in this case, is to make the `out` parameter optional, i.e.

```python
def _call(self, x, out=None):
    out = 77
    return out
```

```
[[-0.804375399659]]
[[77.0]]
```

with that said, then you also need to support the case where `out` is given, so the above would be wrong:

```python
>>> print(Prox(1)(x, out=space.zero()))
[[0.0]]  # unexpected
```

so you would need to handle both cases, e.g.

```python
def _call(self, x, out=None):
    if out is None:
        return 77
    else:
        out[:] = 77
```

```
>>> print(Prox(1)(x))
[[77.0]]
>>> print(Prox(1)(x, out=space.zero()))
[[77.0]]
```

with that said, using the `out` parameter is a really minor optimization that is basically only needed if you have a memory limited application, so in general you should stick to the classic `_call(x)` definition.

##### Improvement on our side

To minimize confusion in this case, we could be more strict in requiring that *if* there is an return value, not equal to `out`, we should raise an error, i.e.

```python
out = op.range.element()
result = op(x, out)
if result is not None and result is not out:
    raise ValueError('`op` returned a different value than result.')
return out
```

**Comment by adler-j** [comment]
Noticed @kohr-h when I was done writing, didn't want to throw it away so somewhat duplicate :/

**Comment by kohr-h** [comment]
Close?
